// Detailed constants and telemetry mock datasets for Model Intelligence Control Centre

export const DAG_NODES_DATA = [
  {
    num: 1,
    id: 'dag-nowcast',
    name: 'Rain Nowcast',
    ver: 'v2.4.2',
    latency: '41.2s',
    gpuMemory: '3.4 GB',
    inputSources: ['IMD S-Band Doppler Radar (Colaba)', 'Dual-Pol ZDR/KDP (0.5°–9.0°)', 'Kalman Filtered AWS Ingest'],
    outputTensors: ['precipitation_rate_250m [12, 1, 400, 400]', 'motion_vectors_trec [2, 400, 400]', 'nowcast_uncertainty_bounds [12, 400, 400]'],
    computeBackend: 'CUDA 12.2 / PyTorch 2.3 ConvLSTM + DGMR Ensemble',
    batchSize: 1,
    precision: 'FP16 Mixed Precision',
    description: 'Extrapolates radar convective plumes up to +180 minutes using recurrent ConvLSTM with optical flow constraint.',
    status: 'OPERATIONAL',
    loss: '0.0182 MSE',
    throughput: '3.8 FPS (mesh batches)',
  },
  {
    num: 2,
    id: 'dag-infiltration',
    name: 'Runoff Infiltration',
    ver: 'v2.1.0',
    latency: '8.4s',
    gpuMemory: '1.2 GB',
    inputSources: ['precipitation_rate_250m', 'Sentinel-2 Impervious Surface Grid', 'Green-Ampt Soil Saturation Mesh'],
    outputTensors: ['net_surface_runoff_flux [12, 400, 400]', 'soil_suction_head [400, 400]', 'percolation_loss [400, 400]'],
    computeBackend: 'C++ SIMD Green-Ampt Hydrodynamic Kernel',
    batchSize: 12,
    precision: 'FP32 High Precision',
    description: 'Calculates soil suction head, infiltration loss, and effective surface excess runoff volume across 24 municipal wards.',
    status: 'OPERATIONAL',
    loss: '0.0094 MAE',
    throughput: '14.2 MPixels/s',
  },
  {
    num: 3,
    id: 'dag-swe2d',
    name: '2D Surface Flow',
    ver: 'v1.8.0',
    latency: '34.8s',
    gpuMemory: '7.8 GB',
    inputSources: ['net_surface_runoff_flux', 'LiDAR 5m Bare-Earth DEM', 'Manning Roughness Coefficient Matrix'],
    outputTensors: ['water_depth_grid [12, 400, 400]', 'velocity_u_v [12, 2, 400, 400]', 'froude_number_map [12, 400, 400]'],
    computeBackend: 'Hydro-PINN Graph Neural Surrogate + Roe Riemann GPU Solver',
    batchSize: 1,
    precision: 'FP16 TensorRT Engine',
    description: 'Solves 2D Saint-Venant shallow water equations with sub-grid urban macro-roughness and slope acceleration.',
    status: 'OPERATIONAL',
    loss: '0.0211 RelL2',
    throughput: '1.24x Real-time',
  },
  {
    num: 4,
    id: 'dag-swmm',
    name: 'Drainage Hydraulics',
    ver: 'v1.5.3',
    latency: '18.2s',
    gpuMemory: '2.1 GB',
    inputSources: ['1,428 Storm Conduits Graph', 'Inlet Catchment Runoff Tensors', 'Arabian Sea Tide Height (4.25m MSL)'],
    outputTensors: ['conduit_flow_m3s [1428]', 'manhole_hydraulic_grade [1428]', 'pipe_capacity_utilization [1428]'],
    computeBackend: 'EPA-SWMM 5.2 Dynamic Wave C-Library (OpenMP 16-Core)',
    batchSize: 1,
    precision: 'Double (Float64)',
    description: 'Models dynamic wave backpressure, conduit gravity friction, drop junctions, and tidal flap gate lockout.',
    status: 'OPERATIONAL',
    loss: '0.0031 Flow Dev',
    throughput: '78 kSteps/s',
  },
  {
    num: 5,
    id: 'dag-surcharge',
    name: 'Surcharge & Backflow',
    ver: 'v2.0.1',
    latency: '6.4s',
    gpuMemory: '1.8 GB',
    inputSources: ['conduit_flow_m3s', 'manhole_hydraulic_grade', 'IoT Ultrasonic Piezometers'],
    outputTensors: ['manhole_overflow_flux [1428]', 'street_egress_probability [1428]', 'geyser_hazard_index [1428]'],
    computeBackend: 'Physics-Informed Graph Convolution Network (GCN)',
    batchSize: 4,
    precision: 'FP16',
    description: 'Predicts pressurized manhole geysering, stormwater egress onto roadways, and subterranean backwater surges.',
    status: 'OPERATIONAL',
    loss: '0.0140 BCE',
    throughput: '220 graphs/s',
  },
  {
    num: 6,
    id: 'dag-depthmesh',
    name: 'Flood Depth Mesh',
    ver: 'v3.1.0',
    latency: '12.0s',
    gpuMemory: '4.2 GB',
    inputSources: ['water_depth_grid', 'manhole_overflow_flux', 'CCTV Video Water Mark Annotations'],
    outputTensors: ['calibrated_depth_mesh [12, 400, 400]', 'inundation_boundary_geojson', 'depth_uncertainty_sigma [400, 400]'],
    computeBackend: 'Multi-Modal Spatial Transformer with Kalmar Ground Tie-in',
    batchSize: 1,
    precision: 'FP16',
    description: 'Fuses 2D overland flow, surcharging manhole discharges, and physical IoT ground sensors into sub-meter street depth.',
    status: 'MONITORING',
    loss: '1.9 cm MAE',
    throughput: '8.4 frames/s',
  },
  {
    num: 7,
    id: 'dag-risk',
    name: 'Risk Engine',
    ver: 'v2.8.4',
    latency: '4.1s',
    gpuMemory: '0.9 GB',
    inputSources: ['calibrated_depth_mesh', '2,400+ Critical Assets GIS', 'Live Demographic Density Grids'],
    outputTensors: ['ward_hazard_indices [24]', 'critical_asset_exposure_flags [180]', 'impact_severity_class [24]'],
    computeBackend: 'Vectorized Spatial Vulnerability Indexer',
    batchSize: 24,
    precision: 'FP32',
    description: 'Multi-criteria spatial overlay computing asset vulnerability, electrical substation exposure, and hospital accessibility.',
    status: 'OPERATIONAL',
    loss: '0.0012 Var',
    throughput: '58 kAssets/s',
  },
  {
    num: 8,
    id: 'dag-routing',
    name: 'Safe Routing',
    ver: 'v3.4.2',
    latency: '0.04s',
    gpuMemory: '0.5 GB',
    inputSources: ['calibrated_depth_mesh', 'Road Network Graph (2,840 km)', 'Emergency Fleet Vehicle Clearance Specs'],
    outputTensors: ['safe_corridor_isochrones', 'evacuation_turn_by_turn_geojson', 'traversability_cost_matrix'],
    computeBackend: 'Contraction Hierarchies + Time-Expanded Dynamic Dijkstra',
    batchSize: 128,
    precision: 'Int32 Graph Index',
    description: 'Dynamically computes dry & safe transit paths for ambulances, fire engines, NDRF rescue trucks, and civilian cars.',
    status: 'OPERATIONAL',
    loss: '0.000 ms Fail',
    throughput: '2,400 queries/s',
  },
];

export const EXTENDED_ML_MODELS = [
  {
    id: 'nowcast-v24',
    name: 'Rainfall Doppler Nowcast Engine',
    version: 'v2.4.2-prod',
    architecture: 'Dual-Pol Doppler Radar + ConvLSTM Extrapolation',
    status: 'OPERATIONAL',
    latency: '41.2s',
    confidence: '91.4%',
    lastRun: '18:31:00 IST (1.5m ago)',
    inputs: 'IMD S-Band Doppler Radar (Dual-Pol 0.5° Scan)',
    outputs: '0–3hr Gridded Precipitation Field (250m Mesh)',
    mae: '1.8 mm/h',
    correlation: '94.2%',
    framework: 'PyTorch 2.3 + TensorRT 10.0',
    weightsSize: '284 MB',
    parameters: '42.8M params',
    f1Score: '0.912',
    aucRoc: '0.965',
    csi: '0.842',
    trainingMonsoons: '2015–2025 (10 Seasons)',
    leadTime: '180 min',
    domain: 'Meteorology & Radar Physics',
    hardware: '2x NVIDIA A100 SXM4 80GB',
  },
  {
    id: 'swe-2d',
    name: '2D Overland Shallow Water Equations (SWE)',
    version: 'v1.8.0-gpu',
    architecture: 'CUDA Finite Volume Discontinuous Galerkin',
    status: 'OPERATIONAL',
    latency: '34.8s',
    confidence: '94.6%',
    lastRun: '18:31:12 IST (1.3m ago)',
    inputs: 'LiDAR 5m DEM + Radar Infiltration Net Runoff',
    outputs: '2D Depth, Velocity Vectors & Ponding Depressions',
    mae: '2.1 cm',
    correlation: '95.8%',
    framework: 'CUDA C++ / OpenACC + PyTorch JIT',
    weightsSize: '142 MB',
    parameters: '18.4M params',
    f1Score: '0.948',
    aucRoc: '0.978',
    csi: '0.871',
    trainingMonsoons: 'Synthetic LiDAR + 2019–2024 Floods',
    leadTime: '120 min',
    domain: 'Hydrodynamic Fluid Dynamics',
    hardware: '4x NVIDIA RTX 6000 Ada',
  },
  {
    id: 'swmm-drainage',
    name: 'Urban Drainage Hydraulic Network Engine',
    version: 'v1.5.3-core',
    architecture: '1D Dynamic Wave Saint-Venant Solver (SWMM Core)',
    status: 'OPERATIONAL',
    latency: '18.2s',
    confidence: '89.2%',
    lastRun: '18:31:25 IST (1.1m ago)',
    inputs: '1,428 Conduit Graph + Tide Level (4.25m MSL)',
    outputs: 'Pipe Hydraulic Saturation & Manhole Surcharge Nodes',
    mae: '0.04 m³/s',
    correlation: '91.0%',
    framework: 'EPA-SWMM Engine compiled to WASM/Native C',
    weightsSize: '68 MB (Topology Graph + Calibration)',
    parameters: 'N/A (Physics Engine)',
    f1Score: '0.898',
    aucRoc: '0.932',
    csi: '0.825',
    trainingMonsoons: 'Hydraulic Model Calibrated 2021–2025',
    leadTime: '180 min',
    domain: 'Subsurface Stormwater Hydraulics',
    hardware: 'AMD EPYC 7763 64-Core Server',
  },
  {
    id: 'surcharge-pinn',
    name: 'Surcharge & Backflow Predictor',
    version: 'v2.0.1',
    architecture: 'Physics-Informed Graph Neural Network (Hydro-PINN)',
    status: 'OPERATIONAL',
    latency: '6.4s',
    confidence: '92.8%',
    lastRun: '18:31:35 IST (45s ago)',
    inputs: 'Dynamic Hydraulic Head Differentials',
    outputs: 'Backflow Hazard Probability & Street Egress Points',
    mae: '2.4 cm',
    correlation: '93.5%',
    framework: 'PyTorch Geometric + DeepXDE PINN',
    weightsSize: '96 MB',
    parameters: '12.1M params',
    f1Score: '0.931',
    aucRoc: '0.954',
    csi: '0.860',
    trainingMonsoons: 'Historical Pressure Transducer Telemetry',
    leadTime: '60 min',
    domain: 'Pressurized Pipe Backflow & GNN',
    hardware: '1x NVIDIA A100 SXM4 80GB',
  },
  {
    id: 'flood-depth-classifier',
    name: 'Street Flood Depth & Hazard Classifier',
    version: 'v3.1.0',
    architecture: 'Multi-Modal Inundation Transformer Ensemble',
    status: 'MONITORING',
    latency: '12.0s',
    confidence: '95.1%',
    lastRun: '18:31:42 IST (38s ago)',
    inputs: 'SWE Surface Grid + Surcharging Manholes + IoT Gauges',
    outputs: 'Street-Level Flood Risk & Impassability Envelopes',
    mae: '1.9 cm',
    correlation: '96.2%',
    framework: 'HuggingFace Transformers + ONNX Runtime',
    weightsSize: '340 MB',
    parameters: '86.5M params',
    f1Score: '0.954',
    aucRoc: '0.982',
    csi: '0.895',
    trainingMonsoons: 'Full City Telemetry 2017–2025',
    leadTime: '120 min',
    domain: 'Multi-Modal Spatial Inundation',
    hardware: '2x NVIDIA A10G Tensor Core',
  },
  {
    id: 'mobility-router',
    name: 'Flood-Aware Emergency Mobility Engine',
    version: 'v3.4.2',
    architecture: 'Dynamic Time-Expanded Dijkstra + Clearance Constrained',
    status: 'OPERATIONAL',
    latency: '0.04s (38ms)',
    confidence: '99.0%',
    lastRun: 'Continuous (<1s)',
    inputs: 'Live Road Submergence + Fleet Vehicle Specifications',
    outputs: 'Turn-by-Turn Safe Routing Vectors & CAD GeoJSON',
    mae: '0.0 min',
    correlation: '99.2%',
    framework: 'Rust Native + Valhalla Graph Router',
    weightsSize: '512 MB (Road Graph with Inundation Weights)',
    parameters: 'N/A (Algorithmic Contraction Graph)',
    f1Score: '0.992',
    aucRoc: '0.998',
    csi: '0.985',
    trainingMonsoons: 'Daily GIS Road Topology Sync',
    leadTime: 'Real-time (0–60 min dynamic)',
    domain: 'Emergency Graph Routing',
    hardware: 'Dual Intel Xeon Platinum 8380',
  },
];

export const SENSOR_GROUND_TRUTH_LOG = [
  { id: 'SN-01', location: 'Hindmata Dadar Underpass', predicted: 29.4, observed: 28.6, delta: '+0.8 cm', status: 'OPTIMAL', r2: 0.962 },
  { id: 'SN-02', location: 'Milan Subway Santacruz', predicted: 42.1, observed: 43.0, delta: '-0.9 cm', status: 'OPTIMAL', r2: 0.958 },
  { id: 'SN-03', location: 'Kurla West Kranti Nagar', predicted: 51.0, observed: 49.8, delta: '+1.2 cm', status: 'WARN_DRIFT', r2: 0.931 },
  { id: 'SN-04', location: 'King Circle Gandhi Market', predicted: 36.2, observed: 35.5, delta: '+0.7 cm', status: 'OPTIMAL', r2: 0.968 },
  { id: 'SN-05', location: 'Sion Railway Culvert', predicted: 38.9, observed: 40.2, delta: '-1.3 cm', status: 'WARN_DRIFT', r2: 0.924 },
  { id: 'SN-06', location: 'Andheri Subway SV Road', predicted: 48.5, observed: 48.0, delta: '+0.5 cm', status: 'OPTIMAL', r2: 0.974 },
  { id: 'SN-07', location: 'Bandra-Kurla Complex MTNL', predicted: 14.2, observed: 13.9, delta: '+0.3 cm', status: 'OPTIMAL', r2: 0.981 },
  { id: 'SN-08', location: 'Chunabhatti Railway Subway', predicted: 31.8, observed: 30.9, delta: '+0.9 cm', status: 'OPTIMAL', r2: 0.952 },
];

export const DRIFT_FEATURES_MATRIX = [
  { feature: 'Doppler ZDR Reflectivity (dBZ)', psi: 0.038, wasserstein: 0.042, status: 'STABLE', driftRisk: 'Low' },
  { feature: 'Rainfall Intensity (mm/hr)', psi: 0.082, wasserstein: 0.091, status: 'STABLE', driftRisk: 'Low' },
  { feature: 'Arabian Sea Tide Height (m MSL)', psi: 0.045, wasserstein: 0.039, status: 'STABLE', driftRisk: 'Low' },
  { feature: 'Runoff Soil Infiltration Rate (mm/h)', psi: 0.128, wasserstein: 0.145, status: 'MODERATE_SHIFT', driftRisk: 'Medium' },
  { feature: 'Manhole Hydraulic Head Pressure (m)', psi: 0.095, wasserstein: 0.104, status: 'STABLE', driftRisk: 'Low' },
  { feature: 'CCTV Surface Water Segment Area (%)', psi: 0.264, wasserstein: 0.288, status: 'SEVERE_SHIFT', driftRisk: 'High (Water reflection glare)' },
];

export const CANARY_CONFIG_DEFAULT = {
  activeProdVersion: 'v2.4.2-prod',
  candidateVersion: 'v2.5.0-rc3 (Transformer Hybrid)',
  trafficSplitPct: 15,
  prodErrorRate: '0.04%',
  candidateErrorRate: '0.06%',
  prodLatency: '41.2s',
  candidateLatency: '28.4s (-31% faster)',
  rollbackThreshold: '0.50% error rate or >60s latency',
};

