// Comprehensive Drainage & Hydraulic Engineering Constants & Dataset for Mumbai Municipal Corporation (BMC)

export const EXTENDED_DRAINAGE_NODES = [
  {
    id: 'D-204',
    name: 'Node D-204 (Kurla West Drop Junction)',
    type: 'Stormwater Junction (RC Box Culvert)',
    ward: 'Ward L',
    connectedPipes: 7,
    currentLoad: 87.4,
    baseLoad: 87.4,
    capacity: 100.0,
    maxFlow: '14.2 m³/s',
    conduitShape: 'Box 3.2m x 2.4m',
    diameterM: 3.2,
    invertLevel: 2.10,
    surfaceElevation: 6.20,
    upstreamInflow: 16.8,
    downstreamThrottle: 'Flap-gate F-09 submerged by high tide (+0.38 bar backpressure)',
    throttlePct: 78,
    siltPercentage: 42,
    froudeNumber: 0.74,
    velocityMs: 2.15,
    hglElevation: 5.65,
    pressureKPa: 34.8,
    status: 'NEAR SURCHARGE',
    predictedSurcharge: '19:17 IST',
    coordinates: [72.8812, 19.0668],
    catchmentAreaHa: 124.5,
    runoffCoeff: 0.82,
    manningN: 0.016,
    slope: 0.0025,
  },
  {
    id: 'C-118',
    name: 'Node C-118 (Sion Ambedkar Trunk Confluence)',
    type: 'Major Arterial Box Culvert',
    ward: 'Ward F/N',
    connectedPipes: 5,
    currentLoad: 94.2,
    baseLoad: 94.2,
    capacity: 100.0,
    maxFlow: '18.5 m³/s',
    conduitShape: 'Twin Box 2.8m x 2.8m',
    diameterM: 3.5,
    invertLevel: 1.40,
    surfaceElevation: 4.80,
    upstreamInflow: 21.0,
    downstreamThrottle: 'Mithi River High Tide Barrier (Tide: 4.25m MSL)',
    throttlePct: 88,
    siltPercentage: 54,
    froudeNumber: 0.89,
    velocityMs: 2.45,
    hglElevation: 4.60,
    pressureKPa: 41.2,
    status: 'SURCHARGING',
    predictedSurcharge: '18:55 IST',
    coordinates: [72.8634, 19.0412],
    catchmentAreaHa: 168.0,
    runoffCoeff: 0.88,
    manningN: 0.018,
    slope: 0.0018,
  },
  {
    id: 'M-042',
    name: 'Node M-042 (Andheri Metro Line Conduit)',
    type: 'Stormwater Lateral Sump',
    ward: 'Ward K/E',
    connectedPipes: 4,
    currentLoad: 72.1,
    baseLoad: 72.1,
    capacity: 100.0,
    maxFlow: '8.4 m³/s',
    conduitShape: 'Circular Ø 2.2m',
    diameterM: 2.2,
    invertLevel: 3.60,
    surfaceElevation: 8.10,
    upstreamInflow: 6.1,
    downstreamThrottle: 'Unrestricted gravity discharge',
    throttlePct: 40,
    siltPercentage: 18,
    froudeNumber: 0.58,
    velocityMs: 1.62,
    hglElevation: 6.20,
    pressureKPa: 25.5,
    status: 'NORMAL CAPACITY',
    predictedSurcharge: 'None (<21:00)',
    coordinates: [72.8512, 19.1174],
    catchmentAreaHa: 85.0,
    runoffCoeff: 0.79,
    manningN: 0.013,
    slope: 0.0035,
  },
  {
    id: 'G-014',
    name: 'Node G-014 (Dadar Hindmata Outfall Sump)',
    type: 'Underground Holding Chamber',
    ward: 'Ward G/N',
    connectedPipes: 6,
    currentLoad: 88.0,
    baseLoad: 88.0,
    capacity: 100.0,
    maxFlow: '12.0 m³/s',
    conduitShape: 'Vault Chamber 4.0m x 3.0m',
    diameterM: 4.0,
    invertLevel: 1.10,
    surfaceElevation: 4.50,
    upstreamInflow: 13.2,
    downstreamThrottle: 'Dewatering pumps active at 85% capacity',
    throttlePct: 75,
    siltPercentage: 36,
    froudeNumber: 0.65,
    velocityMs: 1.88,
    hglElevation: 4.15,
    pressureKPa: 32.1,
    status: 'NEAR SURCHARGE',
    predictedSurcharge: '19:08 IST',
    coordinates: [72.8450, 19.0162],
    catchmentAreaHa: 110.2,
    runoffCoeff: 0.85,
    manningN: 0.015,
    slope: 0.0015,
  },
  {
    id: 'S-305',
    name: 'Node S-305 (Milan Subway Invert Sump)',
    type: 'Low-Depression Sump Pit',
    ward: 'Ward H/W',
    connectedPipes: 4,
    currentLoad: 96.5,
    baseLoad: 96.5,
    capacity: 100.0,
    maxFlow: '7.8 m³/s',
    conduitShape: 'Concrete Sump 3.0m x 2.5m',
    diameterM: 2.8,
    invertLevel: -0.40,
    surfaceElevation: 3.20,
    upstreamInflow: 9.4,
    downstreamThrottle: 'Severe road depression inflow funneling',
    throttlePct: 92,
    siltPercentage: 45,
    froudeNumber: 0.92,
    velocityMs: 2.65,
    hglElevation: 3.10,
    pressureKPa: 44.5,
    status: 'SURCHARGING',
    predictedSurcharge: '18:48 IST',
    coordinates: [72.8427, 19.0883],
    catchmentAreaHa: 62.0,
    runoffCoeff: 0.90,
    manningN: 0.017,
    slope: 0.0042,
  },
  {
    id: 'O-088',
    name: 'Node O-088 (Mahim Creek Tidal Outfall)',
    type: 'Tidal Sluice Flap Outfall',
    ward: 'Ward G/N',
    connectedPipes: 8,
    currentLoad: 91.0,
    baseLoad: 91.0,
    capacity: 100.0,
    maxFlow: '32.0 m³/s',
    conduitShape: 'Quadruple Box 4x(2.5m x 2.5m)',
    diameterM: 5.0,
    invertLevel: 0.20,
    surfaceElevation: 3.80,
    upstreamInflow: 34.5,
    downstreamThrottle: 'High tide seawater ingress lockout (Gate 4 shut)',
    throttlePct: 85,
    siltPercentage: 48,
    froudeNumber: 0.42,
    velocityMs: 1.35,
    hglElevation: 3.65,
    pressureKPa: 38.0,
    status: 'SURCHARGING',
    predictedSurcharge: '18:58 IST',
    coordinates: [72.8350, 19.0400],
    catchmentAreaHa: 340.0,
    runoffCoeff: 0.81,
    manningN: 0.019,
    slope: 0.0008,
  },
  {
    id: 'DH-07',
    name: 'Node DH-07 (Dharavi 90-Feet Road Canal)',
    type: 'Open Masonry Channel with Drop Pit',
    ward: 'Ward G/N',
    connectedPipes: 5,
    currentLoad: 84.0,
    baseLoad: 84.0,
    capacity: 100.0,
    maxFlow: '15.6 m³/s',
    conduitShape: 'Trapezoidal Channel 5m base',
    diameterM: 4.2,
    invertLevel: 1.80,
    surfaceElevation: 5.20,
    upstreamInflow: 14.8,
    downstreamThrottle: 'Solid waste accumulation at culvert mouth',
    throttlePct: 70,
    siltPercentage: 58,
    froudeNumber: 0.61,
    velocityMs: 1.72,
    hglElevation: 4.70,
    pressureKPa: 29.4,
    status: 'NEAR SURCHARGE',
    predictedSurcharge: '19:24 IST',
    coordinates: [72.8550, 19.0450],
    catchmentAreaHa: 145.0,
    runoffCoeff: 0.86,
    manningN: 0.024,
    slope: 0.0016,
  },
  {
    id: 'BKC-03',
    name: 'Node BKC-03 (Vakola Nullah Confluence)',
    type: 'Sub-Arterial Confluence Structure',
    ward: 'Ward H/E',
    connectedPipes: 6,
    currentLoad: 68.5,
    baseLoad: 68.5,
    capacity: 100.0,
    maxFlow: '24.0 m³/s',
    conduitShape: 'Twin Box 3.5m x 3.0m',
    diameterM: 4.5,
    invertLevel: 1.60,
    surfaceElevation: 6.80,
    upstreamInflow: 18.2,
    downstreamThrottle: 'Holding pond diversion gate open at 50%',
    throttlePct: 45,
    siltPercentage: 22,
    froudeNumber: 0.69,
    velocityMs: 2.05,
    hglElevation: 4.80,
    pressureKPa: 21.0,
    status: 'NORMAL CAPACITY',
    predictedSurcharge: 'None (<22:00)',
    coordinates: [72.8640, 19.0620],
    catchmentAreaHa: 210.0,
    runoffCoeff: 0.77,
    manningN: 0.015,
    slope: 0.0022,
  },
  {
    id: 'KC-101',
    name: 'Node KC-101 (King’s Circle Gandhi Market Deep Sump)',
    type: 'Deep Underground Box Drain',
    ward: 'Ward F/N',
    connectedPipes: 6,
    currentLoad: 92.8,
    baseLoad: 92.8,
    capacity: 100.0,
    maxFlow: '11.5 m³/s',
    conduitShape: 'Box Culvert 3.0m x 2.2m',
    diameterM: 3.0,
    invertLevel: 0.85,
    surfaceElevation: 4.10,
    upstreamInflow: 12.8,
    downstreamThrottle: 'Backwater wave propagation from Britannia Pumping outfall',
    throttlePct: 82,
    siltPercentage: 51,
    froudeNumber: 0.82,
    velocityMs: 2.30,
    hglElevation: 3.95,
    pressureKPa: 37.6,
    status: 'SURCHARGING',
    predictedSurcharge: '18:50 IST',
    coordinates: [72.8580, 19.0310],
    catchmentAreaHa: 98.0,
    runoffCoeff: 0.89,
    manningN: 0.017,
    slope: 0.0012,
  },
  {
    id: 'CH-22',
    name: 'Node CH-22 (Chembur Nullah Trunk Junction)',
    type: 'Stormwater Trunk Confluence',
    ward: 'Ward M/W',
    connectedPipes: 5,
    currentLoad: 64.0,
    baseLoad: 64.0,
    capacity: 100.0,
    maxFlow: '16.0 m³/s',
    conduitShape: 'Box 3.0m x 2.6m',
    diameterM: 3.2,
    invertLevel: 2.80,
    surfaceElevation: 7.90,
    upstreamInflow: 11.2,
    downstreamThrottle: 'Smooth flow to Mahul Creek',
    throttlePct: 35,
    siltPercentage: 20,
    froudeNumber: 0.55,
    velocityMs: 1.55,
    hglElevation: 5.20,
    pressureKPa: 18.2,
    status: 'NORMAL CAPACITY',
    predictedSurcharge: 'None (<23:00)',
    coordinates: [72.8950, 19.0550],
    catchmentAreaHa: 135.0,
    runoffCoeff: 0.74,
    manningN: 0.014,
    slope: 0.0030,
  },
  {
    id: 'SC-55',
    name: 'Node SC-55 (Santacruz Airfield Lateral Sump)',
    type: 'Airport Runway Interceptor Sump',
    ward: 'Ward H/E',
    connectedPipes: 4,
    currentLoad: 76.0,
    baseLoad: 76.0,
    capacity: 100.0,
    maxFlow: '9.2 m³/s',
    conduitShape: 'Twin Box 2.2m x 2.0m',
    diameterM: 2.6,
    invertLevel: 2.40,
    surfaceElevation: 6.90,
    upstreamInflow: 8.0,
    downstreamThrottle: 'Secondary pump P-03 balancing load',
    throttlePct: 52,
    siltPercentage: 25,
    froudeNumber: 0.62,
    velocityMs: 1.75,
    hglElevation: 5.10,
    pressureKPa: 23.4,
    status: 'NORMAL CAPACITY',
    predictedSurcharge: 'None (<21:30)',
    coordinates: [72.8520, 19.0910],
    catchmentAreaHa: 115.0,
    runoffCoeff: 0.78,
    manningN: 0.015,
    slope: 0.0028,
  },
  {
    id: 'SK-80',
    name: 'Node SK-80 (Sakinaka Industrial Culvert Junction)',
    type: 'Industrial Estate Stormwater Ingress',
    ward: 'Ward L',
    connectedPipes: 6,
    currentLoad: 89.2,
    baseLoad: 89.2,
    capacity: 100.0,
    maxFlow: '13.0 m³/s',
    conduitShape: 'Box Culvert 3.2m x 2.2m',
    diameterM: 3.2,
    invertLevel: 3.10,
    surfaceElevation: 7.80,
    upstreamInflow: 14.5,
    downstreamThrottle: 'High sediment inflow from Powai foothills',
    throttlePct: 76,
    siltPercentage: 49,
    froudeNumber: 0.78,
    velocityMs: 2.22,
    hglElevation: 6.90,
    pressureKPa: 33.2,
    status: 'NEAR SURCHARGE',
    predictedSurcharge: '19:12 IST',
    coordinates: [72.8870, 19.1020],
    catchmentAreaHa: 140.0,
    runoffCoeff: 0.84,
    manningN: 0.021,
    slope: 0.0032,
  },
];

export const BMC_PUMPING_STATIONS = [
  {
    id: 'PS-BRIT',
    name: 'Britannia Stormwater Pumping Station',
    ward: 'Ward F/S',
    location: 'Reay Road / Sewri',
    outfall: 'Arabian Sea (Harbour Coast)',
    totalPumps: 6,
    runningPumps: 5,
    standbyPumps: 1,
    pumpType: 'Vertical Axial Flow (Submersible)',
    ratedCapacity: '36,000 m³/hr',
    dischargeRate: 31200,
    currentLoadPct: 86,
    wetWellDepthM: 3.85,
    maxWetWellM: 4.50,
    vfdFrequencyHz: 48.5,
    powerSource: 'Grid Primary (11kV) + 2x 2500kVA DG Sync',
    fuelBufferHours: 42,
    status: 'OPTIMAL RUNNING',
    pumps: [
      { id: 'P-01', rpm: 740, hz: 50, flowM3h: 6000, tempC: 58, vibrationMmS: 2.1, status: 'RUNNING' },
      { id: 'P-02', rpm: 740, hz: 50, flowM3h: 6000, tempC: 61, vibrationMmS: 2.4, status: 'RUNNING' },
      { id: 'P-03', rpm: 720, hz: 48, flowM3h: 5800, tempC: 59, vibrationMmS: 2.0, status: 'RUNNING' },
      { id: 'P-04', rpm: 740, hz: 50, flowM3h: 6000, tempC: 63, vibrationMmS: 2.6, status: 'RUNNING' },
      { id: 'P-05', rpm: 740, hz: 50, flowM3h: 6000, tempC: 60, vibrationMmS: 2.2, status: 'RUNNING' },
      { id: 'P-06', rpm: 0, hz: 0, flowM3h: 0, tempC: 28, vibrationMmS: 0.0, status: 'STANDBY READY' },
    ],
  },
  {
    id: 'PS-HAJI',
    name: 'Haji Ali Stormwater Pumping Station',
    ward: 'Ward D',
    location: 'Worli Sea Face / Haji Ali Bay',
    outfall: 'Arabian Sea (West Coast)',
    totalPumps: 6,
    runningPumps: 6,
    standbyPumps: 0,
    pumpType: 'Kirloskar High-Capacity Submersible',
    ratedCapacity: '36,000 m³/hr',
    dischargeRate: 35800,
    currentLoadPct: 99,
    wetWellDepthM: 4.10,
    maxWetWellM: 4.20,
    vfdFrequencyHz: 50.0,
    powerSource: 'Dual Grid Feeder + 3x 1800kVA Cummins Genset',
    fuelBufferHours: 36,
    status: 'MAX CONTINUOUS',
    pumps: [
      { id: 'P-01', rpm: 750, hz: 50, flowM3h: 6000, tempC: 64, vibrationMmS: 2.8, status: 'RUNNING' },
      { id: 'P-02', rpm: 750, hz: 50, flowM3h: 6000, tempC: 65, vibrationMmS: 2.9, status: 'RUNNING' },
      { id: 'P-03', rpm: 750, hz: 50, flowM3h: 6000, tempC: 63, vibrationMmS: 2.7, status: 'RUNNING' },
      { id: 'P-04', rpm: 745, hz: 50, flowM3h: 5950, tempC: 66, vibrationMmS: 3.1, status: 'RUNNING' },
      { id: 'P-05', rpm: 745, hz: 50, flowM3h: 5950, tempC: 62, vibrationMmS: 2.5, status: 'RUNNING' },
      { id: 'P-06', rpm: 740, hz: 49, flowM3h: 5900, tempC: 61, vibrationMmS: 2.4, status: 'RUNNING' },
    ],
  },
  {
    id: 'PS-LOVE',
    name: 'Love Grove Pumping Station',
    ward: 'Ward G/S',
    location: 'Worli Nullah Outfall',
    outfall: 'Arabian Sea (Worli Point)',
    totalPumps: 5,
    runningPumps: 4,
    standbyPumps: 1,
    pumpType: 'Heavy Axial Flow Propeller Pump',
    ratedCapacity: '30,000 m³/hr',
    dischargeRate: 24800,
    currentLoadPct: 82,
    wetWellDepthM: 3.40,
    maxWetWellM: 4.20,
    vfdFrequencyHz: 46.0,
    powerSource: 'Tata Power 22kV Dedicated Substation',
    fuelBufferHours: 48,
    status: 'OPTIMAL RUNNING',
    pumps: [
      { id: 'P-01', rpm: 720, hz: 48, flowM3h: 6200, tempC: 57, vibrationMmS: 1.9, status: 'RUNNING' },
      { id: 'P-02', rpm: 720, hz: 48, flowM3h: 6200, tempC: 58, vibrationMmS: 2.0, status: 'RUNNING' },
      { id: 'P-03', rpm: 720, hz: 48, flowM3h: 6200, tempC: 60, vibrationMmS: 2.2, status: 'RUNNING' },
      { id: 'P-04', rpm: 720, hz: 48, flowM3h: 6200, tempC: 59, vibrationMmS: 2.1, status: 'RUNNING' },
      { id: 'P-05', rpm: 0, hz: 0, flowM3h: 0, tempC: 26, vibrationMmS: 0.0, status: 'STANDBY READY' },
    ],
  },
  {
    id: 'PS-CLEAVE',
    name: 'Cleave Land Pumping Station',
    ward: 'Ward G/S',
    location: 'Annie Besant Road, Worli',
    outfall: 'Mahim Bay / Worli Channel',
    totalPumps: 7,
    runningPumps: 6,
    standbyPumps: 1,
    pumpType: 'Submersible Screw Centrifugal',
    ratedCapacity: '42,000 m³/hr',
    dischargeRate: 36400,
    currentLoadPct: 87,
    wetWellDepthM: 3.65,
    maxWetWellM: 4.50,
    vfdFrequencyHz: 49.0,
    powerSource: 'Dual Grid 11kV',
    fuelBufferHours: 40,
    status: 'OPTIMAL RUNNING',
    pumps: [
      { id: 'P-01', rpm: 735, hz: 49, flowM3h: 6000, tempC: 60, vibrationMmS: 2.2, status: 'RUNNING' },
      { id: 'P-02', rpm: 735, hz: 49, flowM3h: 6000, tempC: 61, vibrationMmS: 2.3, status: 'RUNNING' },
      { id: 'P-03', rpm: 735, hz: 49, flowM3h: 6000, tempC: 59, vibrationMmS: 2.1, status: 'RUNNING' },
      { id: 'P-04', rpm: 735, hz: 49, flowM3h: 6000, tempC: 62, vibrationMmS: 2.4, status: 'RUNNING' },
      { id: 'P-05', rpm: 740, hz: 50, flowM3h: 6200, tempC: 64, vibrationMmS: 2.5, status: 'RUNNING' },
      { id: 'P-06', rpm: 740, hz: 50, flowM3h: 6200, tempC: 63, vibrationMmS: 2.4, status: 'RUNNING' },
      { id: 'P-07', rpm: 0, hz: 0, flowM3h: 0, tempC: 27, vibrationMmS: 0.0, status: 'STANDBY READY' },
    ],
  },
  {
    id: 'PS-IRLA',
    name: 'Irla Stormwater Pumping Station',
    ward: 'Ward K/W',
    location: 'Juhu Scheme / Irla Nullah Outfall',
    outfall: 'Arabian Sea (Juhu Coast)',
    totalPumps: 8,
    runningPumps: 7,
    standbyPumps: 1,
    pumpType: 'Variable Pitch Impeller Axial',
    ratedCapacity: '48,000 m³/hr',
    dischargeRate: 43200,
    currentLoadPct: 90,
    wetWellDepthM: 3.90,
    maxWetWellM: 4.40,
    vfdFrequencyHz: 49.5,
    powerSource: 'Adani Electricity 11kV Grid',
    fuelBufferHours: 52,
    status: 'HIGH DISCHARGE',
    pumps: [
      { id: 'P-01', rpm: 740, hz: 50, flowM3h: 6150, tempC: 60, vibrationMmS: 2.3, status: 'RUNNING' },
      { id: 'P-02', rpm: 740, hz: 50, flowM3h: 6150, tempC: 61, vibrationMmS: 2.4, status: 'RUNNING' },
      { id: 'P-03', rpm: 740, hz: 50, flowM3h: 6150, tempC: 62, vibrationMmS: 2.5, status: 'RUNNING' },
      { id: 'P-04', rpm: 740, hz: 50, flowM3h: 6150, tempC: 59, vibrationMmS: 2.1, status: 'RUNNING' },
      { id: 'P-05', rpm: 740, hz: 50, flowM3h: 6150, tempC: 63, vibrationMmS: 2.6, status: 'RUNNING' },
      { id: 'P-06', rpm: 740, hz: 50, flowM3h: 6150, tempC: 60, vibrationMmS: 2.2, status: 'RUNNING' },
      { id: 'P-07', rpm: 740, hz: 50, flowM3h: 6150, tempC: 62, vibrationMmS: 2.3, status: 'RUNNING' },
      { id: 'P-08', rpm: 0, hz: 0, flowM3h: 0, tempC: 25, vibrationMmS: 0.0, status: 'STANDBY READY' },
    ],
  },
  {
    id: 'PS-GAZDAR',
    name: 'Gazdarband Pumping Station',
    ward: 'Ward H/W',
    location: 'Khar Danda / Santacruz Coast',
    outfall: 'Arabian Sea (Khar Danda Creek)',
    totalPumps: 6,
    runningPumps: 5,
    standbyPumps: 1,
    pumpType: 'Submersible Axial Flow',
    ratedCapacity: '36,000 m³/hr',
    dischargeRate: 30500,
    currentLoadPct: 85,
    wetWellDepthM: 3.55,
    maxWetWellM: 4.30,
    vfdFrequencyHz: 48.0,
    powerSource: 'Dual Grid 11kV + 2x DG sets',
    fuelBufferHours: 38,
    status: 'OPTIMAL RUNNING',
    pumps: [
      { id: 'P-01', rpm: 730, hz: 48, flowM3h: 6100, tempC: 58, vibrationMmS: 2.0, status: 'RUNNING' },
      { id: 'P-02', rpm: 730, hz: 48, flowM3h: 6100, tempC: 59, vibrationMmS: 2.1, status: 'RUNNING' },
      { id: 'P-03', rpm: 730, hz: 48, flowM3h: 6100, tempC: 62, vibrationMmS: 2.3, status: 'RUNNING' },
      { id: 'P-04', rpm: 730, hz: 48, flowM3h: 6100, tempC: 60, vibrationMmS: 2.1, status: 'RUNNING' },
      { id: 'P-05', rpm: 730, hz: 48, flowM3h: 6100, tempC: 61, vibrationMmS: 2.2, status: 'RUNNING' },
      { id: 'P-06', rpm: 0, hz: 0, flowM3h: 0, tempC: 29, vibrationMmS: 0.0, status: 'STANDBY READY' },
    ],
  },
];

export const TIDAL_SLUICE_GATES = [
  {
    id: 'SG-MAHIM-01',
    name: 'Mahim Bay Sluice Flap Gate #1',
    location: 'Mahim Creek Outfall',
    seaLevelMSL: 4.25,
    drainLevelMSL: 3.90,
    differentialHeadM: -0.35,
    gateAngleDeg: 12,
    autoStatus: 'SHUT (TIDAL BACKPRESSURE)',
    dischargeM3s: 0.0,
    gateWidthM: 4.5,
    gateHeightM: 3.5,
    lockoutRisk: 'CRITICAL LOCKOUT',
    gravityWindowNext: '22:15 IST (Tide drops < 3.2m)',
  },
  {
    id: 'SG-MAHIM-02',
    name: 'Mahim Bay Sluice Flap Gate #2 (Aux Bypass)',
    location: 'Mahim Creek Outfall',
    seaLevelMSL: 4.25,
    drainLevelMSL: 4.40,
    differentialHeadM: 0.15,
    gateAngleDeg: 45,
    autoStatus: 'PARTIAL GRAVITY DISCHARGE',
    dischargeM3s: 14.8,
    gateWidthM: 4.5,
    gateHeightM: 3.5,
    lockoutRisk: 'MODERATE RISK',
    gravityWindowNext: 'Active until 19:30 IST',
  },
  {
    id: 'SG-WORLI-01',
    name: 'Worli Point Outfall Radial Gate',
    location: 'Worli Point Sea Wall',
    seaLevelMSL: 4.25,
    drainLevelMSL: 4.60,
    differentialHeadM: 0.35,
    gateAngleDeg: 68,
    autoStatus: 'DISCHARGING UNDER GRAVITY',
    dischargeM3s: 22.4,
    gateWidthM: 6.0,
    gateHeightM: 4.0,
    lockoutRisk: 'SAFE DISCHARGE',
    gravityWindowNext: 'Active until 19:40 IST',
  },
  {
    id: 'SG-DHARAVI-03',
    name: 'Dharavi Nullah Non-Return Flap Gate',
    location: 'Mithi River Lower Estuary',
    seaLevelMSL: 4.30,
    drainLevelMSL: 3.75,
    differentialHeadM: -0.55,
    gateAngleDeg: 4,
    autoStatus: 'FULLY SHUT (LOCKOUT)',
    dischargeM3s: 0.0,
    gateWidthM: 3.8,
    gateHeightM: 3.0,
    lockoutRisk: 'SEVERE BACKFLOW DANGER',
    gravityWindowNext: '22:45 IST',
  },
];

export const RETENTION_BASINS = [
  {
    id: 'RB-DADAR-01',
    name: 'Pramod Mahajan Kala Park Underground Holding Tank',
    ward: 'Ward G/N',
    location: 'Dadar West',
    designCapacityM3: 60000,
    currentVolumeM3: 43200,
    fillPercentage: 72,
    inflowGatePct: 80,
    releaseDischargeRateM3h: 5400,
    waterElevationMSL: 2.85,
    criticalSpillElevationMSL: 3.50,
    estimatedTimeFullMin: 42,
    pumpsInstalled: 4,
    pumpsRunning: 2,
    status: 'ACTIVE RETENTION',
  },
  {
    id: 'RB-STXAV-02',
    name: 'St. Xavier’s Ground Stormwater Retention Sump',
    ward: 'Ward F/N',
    location: 'Parel / Bhoiwada',
    designCapacityM3: 31000,
    currentVolumeM3: 26350,
    fillPercentage: 85,
    inflowGatePct: 90,
    releaseDischargeRateM3h: 3200,
    waterElevationMSL: 3.10,
    criticalSpillElevationMSL: 3.40,
    estimatedTimeFullMin: 18,
    pumpsInstalled: 3,
    pumpsRunning: 3,
    status: 'NEAR CAPACITY (85%)',
  },
  {
    id: 'RB-MILAN-03',
    name: 'Milan Subway Retention Buffer Basin',
    ward: 'Ward H/W',
    location: 'Milan Subway West',
    designCapacityM3: 15000,
    currentVolumeM3: 13950,
    fillPercentage: 93,
    inflowGatePct: 100,
    releaseDischargeRateM3h: 4800,
    waterElevationMSL: -0.10,
    criticalSpillElevationMSL: 0.20,
    estimatedTimeFullMin: 11,
    pumpsInstalled: 3,
    pumpsRunning: 3,
    status: 'CRITICAL BUFFER (93%)',
  },
];

export const DESILTING_TRUCKS = [
  { id: 'SS-01', regNo: 'MH-01-CV-4011', model: 'Super-Sucker 12T Recycler', ward: 'Ward L (Kurla)', status: 'ACTIVE JETTING', location: 'LBS Marg, Kurla West', siltTonsCollected: 8.4, jettingPressureBar: 195, fuelPct: 78, assignedNode: 'D-204' },
  { id: 'SS-02', regNo: 'MH-01-CV-4012', model: 'Super-Sucker 12T Recycler', ward: 'Ward F/N (Sion)', status: 'ACTIVE VACUUMING', location: 'Ambedkar Road, Sion', siltTonsCollected: 10.2, jettingPressureBar: 210, fuelPct: 65, assignedNode: 'C-118' },
  { id: 'SS-03', regNo: 'MH-02-ER-8921', model: 'High-Pressure Jetting Tanker', ward: 'Ward K/E (Andheri)', status: 'EN ROUTE', location: 'Western Express Highway', siltTonsCollected: 4.1, jettingPressureBar: 180, fuelPct: 88, assignedNode: 'M-042' },
  { id: 'SS-04', regNo: 'MH-01-CV-5502', model: 'Super-Sucker 16T Heavy', ward: 'Ward G/N (Dadar)', status: 'ACTIVE JETTING', location: 'Hindmata Flyover Underpass', siltTonsCollected: 12.8, jettingPressureBar: 220, fuelPct: 54, assignedNode: 'G-014' },
  { id: 'SS-05', regNo: 'MH-02-ER-3301', model: 'CCTV Inspection & Desilting', ward: 'Ward H/W (Bandra)', status: 'IDLE / STANDBY', location: 'Bandra Municipal Depot', siltTonsCollected: 0.0, jettingPressureBar: 0, fuelPct: 95, assignedNode: 'S-305' },
  { id: 'SS-06', regNo: 'MH-01-CV-7814', model: 'Super-Sucker 12T Recycler', ward: 'Ward F/N (Matunga)', status: 'ACTIVE VACUUMING', location: 'King’s Circle Circle', siltTonsCollected: 9.6, jettingPressureBar: 205, fuelPct: 70, assignedNode: 'KC-101' },
];

export const IOT_PIEZOMETERS = [
  { id: 'PZM-2041', node: 'D-204', type: 'Hydrostatic Pressure Transducer', depthM: 3.55, maxDepthM: 4.10, pressureKPa: 34.8, tempC: 27.2, batteryPct: 89, loraSignalDbm: -76, status: 'NORMAL TELEMETRY', lastPing: '4s ago' },
  { id: 'PZM-1182', node: 'C-118', type: 'Dual Ultrasonic + Hydrostatic', depthM: 3.20, maxDepthM: 3.40, pressureKPa: 41.2, tempC: 26.8, batteryPct: 94, loraSignalDbm: -82, status: 'HIGH SURCHARGE ALERT', lastPing: '2s ago' },
  { id: 'PZM-0423', node: 'M-042', type: 'Ultrasonic Pulse Echo Level', depthM: 1.80, maxDepthM: 4.50, pressureKPa: 25.5, tempC: 28.1, batteryPct: 77, loraSignalDbm: -68, status: 'NORMAL TELEMETRY', lastPing: '6s ago' },
  { id: 'PZM-0144', node: 'G-014', type: 'Submersible Piezoresistive', depthM: 2.85, maxDepthM: 3.40, pressureKPa: 32.1, tempC: 27.5, batteryPct: 83, loraSignalDbm: -74, status: 'NEAR WARNING HEAD', lastPing: '3s ago' },
  { id: 'PZM-3055', node: 'S-305', type: 'Radar Level Gauge (Non-Contact)', depthM: 3.48, maxDepthM: 3.60, pressureKPa: 44.5, tempC: 26.9, batteryPct: 91, loraSignalDbm: -71, status: 'CRITICAL DEPTH ALARM', lastPing: '1s ago' },
];

export const BAR_SCREENS = [
  { id: 'BS-01', location: 'Mithi River Confluence Screen #1', upstreamHeadM: 2.85, downstreamHeadM: 2.30, deltaHM: 0.55, rakeStatus: 'RAKE ACTIVE (CYCLE #14)', debrisCollectedKg: 640, motorAmps: 18.5, autoTriggerDeltaM: 0.35 },
  { id: 'BS-02', location: 'Irla Nullah Screen #2', upstreamHeadM: 2.40, downstreamHeadM: 2.15, deltaHM: 0.25, rakeStatus: 'STANDBY (CLEAN)', debrisCollectedKg: 410, motorAmps: 0.0, autoTriggerDeltaM: 0.35 },
  { id: 'BS-03', location: 'SNDT Nullah Trash Rack', upstreamHeadM: 2.95, downstreamHeadM: 2.45, deltaHM: 0.50, rakeStatus: 'RAKE ACTIVE (CYCLE #09)', debrisCollectedKg: 890, motorAmps: 21.0, autoTriggerDeltaM: 0.35 },
  { id: 'BS-04', location: 'Love Grove Outfall Screen', upstreamHeadM: 3.10, downstreamHeadM: 2.80, deltaHM: 0.30, rakeStatus: 'STANDBY (CLEAN)', debrisCollectedKg: 320, motorAmps: 0.0, autoTriggerDeltaM: 0.35 },
];

export const WATER_QUALITY_ESTUARINE = [
  { id: 'WQ-MAHIM', name: 'Mahim Bay Marine Outfall', salinityPsu: 28.5, conductMsCm: 44.2, doMgL: 3.2, ph: 7.6, turbidityNtu: 38, tideDirection: 'INCOMING (FLOOD TIDE)', salineWedgeKm: 4.8 },
  { id: 'WQ-MITHI', name: 'Mithi River Lower Estuary', salinityPsu: 18.2, conductMsCm: 29.8, doMgL: 1.8, ph: 7.2, turbidityNtu: 65, tideDirection: 'INCOMING (FLOOD TIDE)', salineWedgeKm: 3.9 },
  { id: 'WQ-WORLI', name: 'Worli Point Deep Sea Outfall', salinityPsu: 32.0, conductMsCm: 48.6, doMgL: 5.6, ph: 7.9, turbidityNtu: 18, tideDirection: 'SLACK HIGH TIDE', salineWedgeKm: 1.2 },
];

export const WARD_DRAINAGE_DEFICITS = [
  { ward: 'Ward L (Kurla / Sakinaka)', capacityM3s: 48.0, peakRunoffM3s: 82.5, deficitPct: -41.8, imperviousPct: 84, slumDensityPct: 62, historicalFloodsPerYr: 14, brimstowadPriority: 'TIER-1 URGENT', capexCrores: 185 },
  { ward: 'Ward F/N (Sion / Matunga)', capacityM3s: 52.0, peakRunoffM3s: 84.0, deficitPct: -38.1, imperviousPct: 88, slumDensityPct: 38, historicalFloodsPerYr: 16, brimstowadPriority: 'TIER-1 URGENT', capexCrores: 210 },
  { ward: 'Ward G/N (Dadar / Mahim)', capacityM3s: 64.0, peakRunoffM3s: 86.0, deficitPct: -25.6, imperviousPct: 82, slumDensityPct: 45, historicalFloodsPerYr: 11, brimstowadPriority: 'TIER-2 HIGH', capexCrores: 140 },
  { ward: 'Ward K/E (Andheri East)', capacityM3s: 70.0, peakRunoffM3s: 88.0, deficitPct: -20.5, imperviousPct: 79, slumDensityPct: 32, historicalFloodsPerYr: 9, brimstowadPriority: 'TIER-2 HIGH', capexCrores: 115 },
  { ward: 'Ward H/W (Bandra / Khar)', capacityM3s: 85.0, peakRunoffM3s: 76.0, deficitPct: 11.8, imperviousPct: 75, slumDensityPct: 24, historicalFloodsPerYr: 4, brimstowadPriority: 'TIER-3 MAINTENANCE', capexCrores: 45 },
  { ward: 'Ward D (Grant Road / Malabar)', capacityM3s: 78.0, peakRunoffM3s: 66.0, deficitPct: 18.2, imperviousPct: 71, slumDensityPct: 18, historicalFloodsPerYr: 3, brimstowadPriority: 'TIER-3 MAINTENANCE', capexCrores: 35 },
];

export const DRAINAGE_SOP_STEPS = [
  { id: 'SOP-01', stage: 'Pre-Storm Readiness (T-3 hrs)', text: 'Verify dewatering pump readiness at all 6 municipal stations with diesel fuel buffer > 36 hrs.', role: 'Chief Mechanical Engineer', checked: true, signoff: 'Er. A. Kulkarni (BMC Mech)' },
  { id: 'SOP-02', stage: 'Pre-Storm Readiness (T-3 hrs)', text: 'Cycle and clear mechanical trash rakes at Irla and Mithi River nullah outfalls.', role: 'Executive Engineer Drainage', checked: true, signoff: 'Er. R. Salvi (Stormwater)' },
  { id: 'SOP-03', stage: 'Tidal Alignment (T-1 hr)', text: 'Inspect tidal non-return flap gates at Mahim and Worli; verify free gravitational movement.', role: 'Sluice Gate Officer', checked: true, signoff: 'Officer V. Shinde' },
  { id: 'SOP-04', stage: 'Storm Onset (T=0)', text: 'Monitor HGL sensors on trunk culverts C-118 and D-204; trigger auxiliary dewatering if HGL > 90%.', role: 'SCADA Telemetry Officer', checked: false, signoff: 'Pending Action' },
  { id: 'SOP-05', stage: 'High Tide Lockout Peak', text: 'Engage 100% forced pumped discharge at Britannia & Haji Ali as sea head exceeds 4.2m MSL.', role: 'Pumping Station Commander', checked: false, signoff: 'Pending Action' },
  { id: 'SOP-06', stage: 'Severe Surcharge Protocol', text: 'Open underground retention basin gates at Pramod Mahajan Park to divert up to 60,000 m³.', role: 'Disaster Cell Director', checked: false, signoff: 'Pending Action' },
  { id: 'SOP-07', stage: 'Post-Flood Desilt Flush', text: 'Dispatch high-pressure jetting units to remove silt deposition from low-elevation box culverts.', role: 'Conservancy Division', checked: false, signoff: 'Pending Action' },
];

