// Extended AI Model Architecture Specs, Datasets, and Constants for Mumbai Flood Intelligence

export const EXTENDED_MODELS_DATA = [
  {
    id: '01',
    code: 'DGMR',
    name: 'Deep Generative Model of Radar',
    category: 'precipitation',
    categoryLabel: 'Precipitation Nowcasting',
    type: 'Deep Learning / Radar GAN',
    architecture: 'Conditional GAN with Spatial & Temporal Discriminators',
    latency: '1.2s',
    leadTime: '0–90 min',
    resolution: '1 km² spatial / 5 min temporal',
    accuracy: '89.4% CSI @ 10mm/h',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 5 min',
    params: '21.4M weights',
    device: 'NVIDIA A100 Tensor Core',
    quantization: 'FP16 Mixed Precision',
    inputs: 'Doppler radar reflectivity (dBZ), satellite infrared radiances',
    outputs: 'Stochastic ensemble radar nowcasts across Greater Mumbai',
    description: 'Probabilistic radar nowcasting capturing sudden convective cell developments, cloudbursts, and rainband trajectories across the Mumbai Doppler domain.',
    role: 'Forecasts incoming radar reflectivity without physics damping.',
    citation: 'Ravuri et al., Nature 2021 (Google DeepMind)',
    layers: [
      { name: 'Input Radar Tensor', shape: '[4, 1, 256, 256]', type: 'Input Layer', params: '0', activation: 'Linear' },
      { name: 'Spatial Conditioning Stack', shape: '[4, 64, 128, 128]', type: 'Gated Residual Conv2D', params: '1.8M', activation: 'GELU' },
      { name: 'Temporal Latent GRU', shape: '[4, 128, 64, 64]', type: 'Convolutional GRU', params: '4.6M', activation: 'Tanh' },
      { name: 'Stochastic Noise Sampler', shape: '[4, 16, 64, 64]', type: 'Gaussian Prior', params: '0', activation: 'N(0, I)' },
      { name: 'Spatial Generator Upsampler', shape: '[18, 1, 256, 256]', type: 'Sub-Pixel Conv2D', params: '15.0M', activation: 'ReLU' }
    ]
  },
  {
    id: '02',
    code: 'RainNet',
    name: 'RainNet Deep Convolutional Network',
    category: 'precipitation',
    categoryLabel: 'Radar Extrapolation',
    type: 'Encoder-Decoder CNN',
    architecture: 'U-Net with Dilated Inception Blocks',
    latency: '0.4s',
    leadTime: '0–60 min',
    resolution: '1 km² / 5 min',
    accuracy: '87.2% Critical Success',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 5 min',
    params: '31.2M weights',
    device: 'Edge RTX 4090 / TensorRT',
    quantization: 'INT8 Quantized',
    inputs: '4-frame sequential radar reflectivity rasters',
    outputs: 'Advective precipitation intensity motion vectors',
    description: 'Convolutional neural network for instantaneous radar advection and storm tracking along the Western Ghats approach.',
    role: 'Identifies advective rainfall motion vectors across suburban corridors.',
    citation: 'Ayzel et al., Geoscientific Model Dev. 2020',
    layers: [
      { name: 'Reflectivity Sequence', shape: '[4, 4, 256, 256]', type: 'Input Layer', params: '0', activation: 'Linear' },
      { name: 'Encoder ConvBlock 1', shape: '[4, 64, 256, 256]', type: 'Conv2D + BatchNorm', params: '2.4M', activation: 'LeakyReLU' },
      { name: 'Encoder ConvBlock 2', shape: '[4, 128, 128, 128]', type: 'Maxpool + Conv2D', params: '5.1M', activation: 'LeakyReLU' },
      { name: 'Bottleneck Dilated Conv', shape: '[4, 256, 64, 64]', type: 'Dilated Residual Conv', params: '11.8M', activation: 'ReLU' },
      { name: 'Decoder TransposeConv', shape: '[4, 1, 256, 256]', type: 'ConvTranspose2D', params: '11.9M', activation: 'Sigmoid' }
    ]
  },
  {
    id: '03',
    code: 'MetNet-2',
    name: 'MetNet-2 Deep Weather Forecasting',
    category: 'precipitation',
    categoryLabel: 'Regional Weather Modeling',
    type: 'Spatial-Temporal Transformer',
    architecture: 'Axial Self-Attention Backbone',
    latency: '2.8s',
    leadTime: '0–3 hours',
    resolution: '1 km² / 2 min',
    accuracy: '91.8% Correlation',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 15 min',
    params: '84.6M weights',
    device: 'Cloud TPU v4 Cluster',
    quantization: 'BFloat16',
    inputs: 'GOES-16 satellite imagery, IMD radar, NWP boundary forecasts',
    outputs: 'Probabilistic precipitation exceedance fields (10, 20, 50 mm/h)',
    description: 'High-capacity neural network synthesizing satellite imagery, Doppler radar, and numerical weather predictions into a unified 3-hour precipitation probability cone.',
    role: 'Provides regional meteorological boundary conditions.',
    citation: 'Espeholt et al., Nature Communications 2022',
    layers: [
      { name: 'Multimodal Satellite & Radar', shape: '[1, 16, 512, 512]', type: 'Multimodal Input', params: '0', activation: 'Linear' },
      { name: 'Patch Partition & Embedding', shape: '[1, 1024, 256]', type: 'Linear Patch Embedding', params: '4.2M', activation: 'LayerNorm' },
      { name: 'Axial Attention Encoders', shape: '[1, 1024, 256]', type: 'Multi-Head Axial Attention (x12)', params: '62.4M', activation: 'GELU' },
      { name: 'Precipitation Probability Head', shape: '[1, 3, 512, 512]', type: 'Softmax Exceedance Head', params: '18.0M', activation: 'Softmax' }
    ]
  },
  {
    id: '04',
    code: 'PySTEPS',
    name: 'PySTEPS Probabilistic Extrapolation',
    category: 'precipitation',
    categoryLabel: 'Optical Flow Nowcasting',
    type: 'Lagrangian S-PROG Ensemble',
    architecture: 'Multi-scale Spectral Decomposition',
    latency: '0.8s',
    leadTime: '0–2 hours',
    resolution: '500m / 5 min',
    accuracy: '86.4% ROC Area',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 5 min',
    params: 'Deterministic / Semi-Lagrangian',
    device: 'Multi-core CPU Parallel OpenMP',
    quantization: 'FP64 Double Precision',
    inputs: 'Lucas-Kanade optical flow vectors from ground weather radar',
    outputs: 'Scale-dependent autoregressive storm velocity cascades',
    description: 'Decomposes precipitation fields across multiple spatial scales with stochastic perturbations to avoid over-smoothing.',
    role: 'Provides ensemble perturbation bounds for sudden cloudbursts.',
    citation: 'Pulkkinen et al., Geoscientific Model Dev. 2019',
    layers: [
      { name: 'Doppler Grid Feed', shape: '[256, 256]', type: 'Raster Grid', params: '0', activation: 'Linear' },
      { name: 'Optical Flow Solver', shape: '[2, 256, 256]', type: 'Lucas-Kanade Advection', params: '0', activation: 'Smooth' },
      { name: 'FFT Bandpass Filter', shape: '[8, 256, 256]', type: 'Fourier Scale Decomposition', params: '0', activation: 'Spectral' },
      { name: 'Autoregressive Cascade', shape: '[30, 256, 256]', type: 'S-PROG Stochastic AR(2)', params: '0', activation: 'Linear' }
    ]
  },
  {
    id: '05',
    code: 'UrbanFloodNet GNN',
    name: 'UrbanFloodNet Graph Neural Network',
    category: 'inundation',
    categoryLabel: 'Street Inundation Surrogate',
    type: 'Spatio-Temporal Graph Neural Network',
    architecture: 'Edge-Conditioned Graph Convolution (ECGCN)',
    latency: '0.15s',
    leadTime: '0–3 hours',
    resolution: 'Street Segment Level (5m)',
    accuracy: '94.8% Nash-Sutcliffe',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Continuous Real-Time',
    params: '12.8M weights',
    device: 'Edge TensorRT GPU',
    quantization: 'INT8 Optimized',
    inputs: 'Street network graph, elevation nodes, 1D SWMM sewer discharge',
    outputs: 'Centimeter-level water depth and surface velocity on every road link',
    description: 'Sub-second neural surrogate for 2D hydrodynamic simulation, mapping topological flow routing over Mumbai street mesh.',
    role: 'Core routing physics engine calculating edge traversal safety.',
    citation: 'Kipf & Welling GCN / Battaglia et al. Relational Inductive Biases',
    layers: [
      { name: 'Road Network Graph', shape: '[48120 nodes, 64 features]', type: 'Graph Feature Matrix', params: '0', activation: 'Linear' },
      { name: 'Edge Conditioned Conv 1', shape: '[48120, 128]', type: 'ECGCN Layer', params: '3.1M', activation: 'ELU' },
      { name: 'Physics Mass Residual Head', shape: '[48120, 128]', type: 'St. Venant Physics Penalty', params: '2.2M', activation: 'Tanh' },
      { name: 'Spatio-Temporal GNN Block', shape: '[48120, 64]', type: 'Message Passing Neural Net', params: '5.4M', activation: 'ReLU' },
      { name: 'Inundation Depth & Velocity', shape: '[48120, 2]', type: 'Regression Head [Depth, Vel]', params: '2.1M', activation: 'ReLU' }
    ]
  },
  {
    id: '06',
    code: 'EPA-SWMM',
    name: 'EPA Storm Water Management Model (1D)',
    category: 'drainage',
    categoryLabel: 'Underground Pipe Hydraulics',
    type: 'Dynamic Wave 1D St. Venant Solver',
    architecture: 'Full St. Venant Dynamic Wave Routing',
    latency: '4.2s',
    leadTime: '0–3 hours',
    resolution: 'Pipe Junctions & Box Drains',
    accuracy: '96.2% Hydrograph Match',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 10 min',
    params: 'Dynamic Hydraulic Solver (18,400 pipes)',
    device: 'Multi-threaded SWMM C-Engine',
    quantization: 'FP64 Double Precision',
    inputs: 'Surface curb inlet flow, underground pipe slopes, flap gate backpressure',
    outputs: 'Manhole surcharging status, hydraulic grade line, pipe flow (m³/s)',
    description: 'Simulates underground sewer network capacity, stormwater pipe surcharge, and surface backflow at low-elevation junctions.',
    role: 'Determines underground drainage choking and manhole overflows.',
    citation: 'Rossman, EPA SWMM 5.1 Manual 2015',
    layers: [
      { name: 'Catchment Hydrology Inflow', shape: '[2400 catchments]', type: 'Subcatchment Runoff', params: '0', activation: 'Non-linear Reservoir' },
      { name: 'Junction Hydraulic Heads', shape: '[14200 manholes]', type: 'Continuity & Conservation', params: '0', activation: 'Implicit Newton-Raphson' },
      { name: 'Dynamic Conduit Flow', shape: '[18400 links]', type: '1D St. Venant Solver', params: '0', activation: 'Manning Equation' }
    ]
  },
  {
    id: '07',
    code: 'LISFLOOD-FP',
    name: 'LISFLOOD-FP 2D Shallow Water Solver',
    category: 'inundation',
    categoryLabel: 'Overland Floodplain Hydrodynamics',
    type: 'Sub-grid 2D St. Venant Solver',
    architecture: 'Inertial Formulation of 2D Shallow Water Equations',
    latency: '8.4s',
    leadTime: '0–6 hours',
    resolution: '5m Raster Mesh',
    accuracy: '93.5% Benchmark Concordance',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 15 min',
    params: 'Inertial Wave Hydrodynamics',
    device: 'NVIDIA CUDA Parallel Raster Kernel',
    quantization: 'FP32 Single Precision',
    inputs: 'CartoDEM 5m elevation, building footprint obstructions, Manning roughness',
    outputs: 'Overland water depth raster (m), momentum flux vectors',
    description: '2D hydrodynamic overland flow solver simulating water ponding in low-lying hollows, railway tracks, and coastal depressions.',
    role: 'Simulates spatial ponding extent and building barrier deflections.',
    citation: 'Bates et al., Journal of Hydrology 2010',
    layers: [
      { name: 'DEM Topography Surface', shape: '[1200, 1600]', type: 'Raster Grid', params: '0', activation: 'Linear' },
      { name: 'Inertial Momentum Solver', shape: '[2, 1200, 1600]', type: 'Sub-grid Momentum Flux', params: '0', activation: 'St. Venant Inertial' },
      { name: 'Ponding Depth Accumulator', shape: '[1200, 1600]', type: 'Mass Continuity Cell Integration', params: '0', activation: 'ReLU' }
    ]
  },
  {
    id: '08',
    code: 'CartoDEM Elevation',
    name: 'ISRO CartoDEM High-Res Topography',
    category: 'terrain',
    categoryLabel: 'Digital Elevation Model',
    type: 'Hydro-Conditioned Micro-Basin Mesh',
    architecture: 'Geodetic Surface Model + Culvert Burn-in',
    latency: 'Static Layer (0ms)',
    leadTime: 'Permanent Baseline',
    resolution: '5m Cell Size / 0.3m Vertical',
    accuracy: '98.9% Geodetic Ground Truth',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Annual Update',
    params: '38M Elevation Nodes',
    device: 'Cloud Spatial Index / GeoTIFF',
    quantization: 'FP32 Geotiff Raster',
    inputs: 'Stereo CARTOSAT photogrammetry, airborne LiDAR, culvert burn-ins',
    outputs: 'Flow accumulation, drainage direction, natural depression sinks',
    description: 'High-resolution digital surface model identifying micro-catchments, railway embankment barriers, and coastal creek basins.',
    role: 'Provides geometric constraint terrain for all surface flow equations.',
    citation: 'ISRO National Remote Sensing Centre (NRSC)',
    layers: [
      { name: 'Cartosat-1 Stereo Triangulation', shape: '[2500, 2500]', type: 'Elevation Matrix', params: '0', activation: 'Linear' },
      { name: 'Hydro-Enforced Stream Burning', shape: '[2500, 2500]', type: 'D8 Flow Routing', params: '0', activation: 'Monotonic' },
      { name: 'Sinks & Depressions Mesh', shape: '[2500, 2500]', type: 'Depression Filling', params: '0', activation: 'Linear' }
    ]
  },
  {
    id: '09',
    code: 'Tidal Harmonics',
    name: 'Arabian Sea Tidal Harmonic Boundary Solver',
    category: 'drainage',
    categoryLabel: 'Coastal Outfall Hydraulics',
    type: 'Harmonic Constituent Hydrodynamic Model',
    architecture: 'T_TIDE Harmonic Analysis & Surge Solver',
    latency: '0.05s',
    leadTime: '0–72 hours',
    resolution: 'Coastal Boundary Gauges',
    accuracy: '99.4% Astronomical Tide Fit',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Continuous Real-Time',
    params: '68 Harmonic Constituents',
    device: 'Lightweight Edge Worker',
    quantization: 'FP64 Double Precision',
    inputs: 'Apollo Bunder & Worli tide gauges, astronomical lunar constituents',
    outputs: 'Tidal sea surface elevation (m MSL), outfall flap gate lockout times',
    description: 'Calculates marine water levels at Mahim Creek, Love Grove, and Haji Ali outfalls to detect gravity drain stalling.',
    role: 'Forecasts outfall gate closures and tidal backpressure hazards.',
    citation: 'Pawlowicz et al., Computers & Geosciences 2002',
    layers: [
      { name: 'Astronomical Lunar/Solar Ephemeris', shape: '[68 constituents]', type: 'Cosine Harmonic Sum', params: '0', activation: 'Trigonometric' },
      { name: 'Meteorological Wind Surge Offset', shape: '[1]', type: 'Ekman Transport Model', params: '0', activation: 'Linear' },
      { name: 'Coastal Sluice Backpressure', shape: '[12 outfalls]', type: 'Hydraulic Gate Headloss', params: '0', activation: 'Orifice Equation' }
    ]
  },
  {
    id: '10',
    code: 'OpenFOAM CFD',
    name: 'OpenFOAM 3D Underpass Vortex Solver',
    category: 'hydraulics',
    categoryLabel: 'Turbulent Flow CFD',
    type: 'Volume of Fluid (VOF) 3D Navier-Stokes',
    architecture: 'k-epsilon Turbulent Multiphase Solver',
    latency: '14.2s (Surrogate Cached)',
    leadTime: '0–60 min',
    resolution: '0.1m Computational Mesh',
    accuracy: '95.1% PIV Laser Calibration',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Triggered upon alert',
    params: 'PINN Surrogate (8.4M weights)',
    device: 'HPC Cluster GPU Nodes',
    quantization: 'FP32 Precision',
    inputs: 'Subway portal geometry, inlet water velocities, drain pump draw',
    outputs: 'Hydrodynamic suction vortex forces, vehicle buoyancy rollover vectors',
    description: 'Detailed 3D fluid dynamic simulation of hazardous water vortex formations at Milan, Khar, and Andheri subways.',
    role: 'Calculates vehicle destabilization and down-force suction risk.',
    citation: 'Weller et al., OpenFOAM CFD Foundation',
    layers: [
      { name: 'Subway Geometry STL Mesh', shape: '[500k cells]', type: '3D Unstructured Mesh', params: '0', activation: 'Linear' },
      { name: 'Navier-Stokes VOF Phase Fraction', shape: '[500k, 3]', type: 'PISO Pressure-Velocity Coupling', params: '0', activation: 'Transport' },
      { name: 'Hydrodynamic Vortex Risk Vector', shape: '[12 danger points]', type: 'Vortex Invariant Q-Criterion', params: '0', activation: 'Threshold' }
    ]
  },
  {
    id: '11',
    code: 'EnKF Fusion',
    name: 'Ensemble Kalman Filter (EnKF) Assimilation',
    category: 'fusion',
    categoryLabel: 'State Estimation & Sensor Fusion',
    type: 'Nonlinear Ensemble Data Assimilation',
    architecture: 'Monte Carlo 100-Member EnKF',
    latency: '0.6s',
    leadTime: 'Continuous Real-Time',
    resolution: 'Point Sensor to Graph Edge',
    accuracy: '97.4% State Convergence',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 30s',
    params: '100 Ensemble State Members',
    device: 'Parallel Multi-core CPU',
    quantization: 'FP64 Double Precision',
    inputs: 'IoT acoustic gauges, Doppler radar, citizen reports, CCTV camera readings',
    outputs: 'Optimal Bayesian estimate of current water depth across all links',
    description: 'Merges multi-source physical sensor measurements and crowdsourced citizen observations into the running hydrologic state.',
    role: 'Maintains single ground truth between predictions and reality.',
    citation: 'Evensen, Ocean Dynamics 2003',
    layers: [
      { name: 'Prior Hydrologic Ensemble', shape: '[100, 48120]', type: 'Model Prior State', params: '0', activation: 'Linear' },
      { name: 'Sensor Innovation Vector', shape: '[48 sensors + 220 reports]', type: 'Observation Operator H', params: '0', activation: 'Linear' },
      { name: 'Kalman Gain & Posterior Update', shape: '[48120]', type: 'Bayesian Minimum Variance', params: '0', activation: 'Kalman Gain' }
    ]
  },
  {
    id: '12',
    code: 'YOLOv8-Flood',
    name: 'YOLOv8-Flood Optical CCTV Level Gauge',
    category: 'sensors',
    categoryLabel: 'Computer Vision Gauging',
    type: 'Deep Convolutional Object & Watermark Detector',
    architecture: 'CSPDarknet with Feature Pyramid Network & Segmentation Mask',
    latency: '0.08s per frame',
    leadTime: 'Real-Time Edge',
    resolution: '1080p Municipal Traffic Feeds',
    accuracy: '93.2% Watermark Segmentation mAP',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Continuous Stream',
    params: '11.2M weights',
    device: 'Edge NVIDIA Jetson Orin',
    quantization: 'INT8 TensorRT Engine',
    inputs: 'Mumbai Traffic Police CCTV camera streams (5,000+ cameras)',
    outputs: 'Detected water edge elevation on curbs, bus tires, and pillars',
    description: 'Edge-deployed computer vision extracting real-time flood watermark levels and submerged vehicle tracking from civic cameras.',
    role: 'Transforms civic cameras into automated water depth sensors.',
    citation: 'Ultralytics YOLOv8 / Lin et al. Semantic Segmentation',
    layers: [
      { name: 'CCTV Video Stream Frame', shape: '[1, 3, 640, 640]', type: 'Camera Ingress', params: '0', activation: 'Linear' },
      { name: 'CSPDarknet Backbone', shape: '[1, 256, 40, 40]', type: 'C2f Spatial Convolution Blocks', params: '4.8M', activation: 'SiLU' },
      { name: 'Waterline Segmentation Head', shape: '[1, 32, 160, 160]', type: 'Proto Mask Generator', params: '3.6M', activation: 'Sigmoid' },
      { name: 'Curb / Tire Reference Metrology', shape: '[1, 1]', type: 'Metric Perspective Projection', params: '2.8M', activation: 'Linear' }
    ]
  },
  {
    id: '13',
    code: 'Geo-BERT NLP',
    name: 'Geo-BERT Citizen NLP Incident Parser',
    category: 'nlp',
    categoryLabel: 'Social & Text Ingestion',
    type: 'Transformer Landmark & Severity Extractor',
    architecture: 'Multilingual BERT fine-tuned on Mumbai Vernacular Toponyms',
    latency: '0.05s',
    leadTime: 'Real-Time Stream',
    resolution: 'Landmark / Cross-street Entity',
    accuracy: '96.8% F1 Named Entity Recognition',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Instant On Submission',
    params: '110M weights',
    device: 'Serverless Cloud Inference',
    quantization: 'ONNX Runtime Dynamic INT8',
    inputs: 'Citizen text reports, vernacular slang (khadda, pani bhara, rail ruka)',
    outputs: 'Structured JSON with coordinate bounding box, depth tag, and hazard flags',
    description: 'Natural language understanding parser resolving colloquial Mumbai locations (e.g., "Gandhi market ke pass", "Dadar TT flyover niche").',
    role: 'Converts unstructured citizen observations into GIS graph pins.',
    citation: 'Devlin et al. BERT / Gururangan et al. Domain Adaptation',
    layers: [
      { name: 'Citizen Report Text Tokens', shape: '[1, 128]', type: 'WordPiece Multilingual Tokenizer', params: '0', activation: 'Embedding' },
      { name: 'Transformer Self-Attention', shape: '[1, 128, 768]', type: '12-Layer Bidirectional Encoders', params: '85.0M', activation: 'GeLU' },
      { name: 'NER Token Classification Head', shape: '[1, 128, 14]', type: 'Token Entity Labeler [B-LOC, I-DEPTH]', params: '12.5M', activation: 'Softmax' },
      { name: 'Gazetteer Geocoding Resolver', shape: '[2]', type: 'Coordinate Disambiguation Head', params: '12.5M', activation: 'Cosine Similarity' }
    ]
  },
  {
    id: '14',
    code: 'A* Dynamic Router',
    name: 'A* Dynamic Multi-Criteria Flood Routing',
    category: 'routing',
    categoryLabel: 'Intelligent Pathfinding',
    type: 'Time-Dependent Constrained A* Search',
    architecture: 'Time-Expanded Directed Acyclic Graph Search with Pareto Fronts',
    latency: '0.12s',
    leadTime: '0–3 hours lookahead',
    resolution: 'Road Network Graph (48,000 links)',
    accuracy: '100% Guaranteed Dry Clearance',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Instant Query',
    params: 'Real-Time Graph Weights Solver',
    device: 'In-Memory Rust / WebAssembly Kernel',
    quantization: 'Native WASM',
    inputs: 'Predicted 0–3h water depth per link, vehicle clearance height, road elevation',
    outputs: 'Optimal safe trajectory minimizing exposure to rising water',
    description: 'Searches space-time graph of Mumbai roads to compute driving routes that remain dry throughout the journey duration.',
    role: 'Generates flood-aware turn-by-turn navigation.',
    citation: 'Hart, Nilsson & Raphael A* / Delling et al. Time-Dependent Routing',
    layers: [
      { name: 'Space-Time Road Graph', shape: '[48120 nodes, 112000 edges]', type: 'Dynamic Adjacency List', params: '0', activation: 'Linear' },
      { name: 'Risk Cost Dynamic Weighting', shape: '[112000]', type: 'Vehicle Clearance vs Water Depth Cost', params: '0', activation: 'Exponential Barrier' },
      { name: 'Bi-directional A* Priority Queue', shape: '[Priority Heap]', type: 'Fibonacci Min-Heap Traversal', params: '0', activation: 'Shortest Safe Path' }
    ]
  },
  {
    id: '15',
    code: 'Evacuation Allocation',
    name: 'Multi-Criteria Shelter & Evacuation Optimizer',
    category: 'routing',
    categoryLabel: 'Civic Shelter Allocation',
    type: 'Linear Programming & Voronoi Network Slicer',
    architecture: 'Mixed-Integer Linear Programming (MILP) with Capacity Constraints',
    latency: '0.35s',
    leadTime: '0–6 hours',
    resolution: 'Ward Relief Hub Level',
    accuracy: 'Optimal Capacity Balancing',
    status: 'ACTIVE_ONLINE',
    updateCycle: 'Every 5 min',
    params: 'Simplex / Interior Point Solver',
    device: 'High-Concurrency Worker',
    quantization: 'FP64 Precision',
    inputs: 'Shelter capacity, medical trauma units, flooded boundary cuts',
    outputs: 'Directs stranded citizens to high-ground havens with vetted dry corridors',
    description: 'Optimizes citizen allocation to emergency shelters, ensuring relief sites are never isolated by rising water.',
    role: 'Powers safe shelter guidance and hospital corridor routing.',
    citation: 'Dantzig Simplex / NDMA National Disaster Management Guidelines',
    layers: [
      { name: 'Shelter Capacities & Vulnerability', shape: '[142 shelters, 8 attributes]', type: 'Civic Facility Matrix', params: '0', activation: 'Linear' },
      { name: 'Flooded Boundary Cut Invariants', shape: '[24 wards]', type: 'Graph Minimum-Cut Formulation', params: '0', activation: 'Boolean Constraints' },
      { name: 'Primal-Dual Simplex Allocator', shape: '[142, 24]', type: 'Optimal Transportation Flow', params: '0', activation: 'Continuous Convex' }
    ]
  }
];

export const MODEL_CATEGORIES = [
  { id: 'all', label: 'All 15 Models', count: 15 },
  { id: 'precipitation', label: 'Rainfall Nowcasting (0–3h)', count: 4 },
  { id: 'inundation', label: 'Hydrologic & Street Mesh', count: 2 },
  { id: 'drainage', label: 'Sewer & Marine Confluence', count: 2 },
  { id: 'sensors', label: 'Sensors & Optical CV', count: 2 },
  { id: 'routing', label: 'Pathfinding & Shelters', count: 2 },
  { id: 'hydraulics', label: 'CFD & Fusion', count: 2 },
  { id: 'terrain', label: 'Elevation Rasters', count: 1 }
];

export const SENSOR_GROUND_TRUTH_DATA = [
  { id: 'SN-01', ward: 'F/North', location: 'Gandhi Market, King’s Circle', sensorType: 'Ultrasonic Pulse', observedDepthCm: 38.5, modelPredCm: 37.2, deltaCm: -1.3, r2: 0.96, batteryPct: 94, status: 'NOMINAL' },
  { id: 'SN-02', ward: 'G/North', location: 'Dadar TT Circle, Flyover Base', sensorType: 'Acoustic Time-of-Flight', observedDepthCm: 44.0, modelPredCm: 45.1, deltaCm: +1.1, r2: 0.95, batteryPct: 88, status: 'NOMINAL' },
  { id: 'SN-03', ward: 'L Ward', location: 'Kurla Station West, Bail Bazar', sensorType: 'Submersible Pressure Transducer', observedDepthCm: 56.2, modelPredCm: 54.8, deltaCm: -1.4, r2: 0.94, batteryPct: 91, status: 'NOMINAL' },
  { id: 'SN-04', ward: 'K/West', location: 'Milan Subway East Portal', sensorType: 'Radar Water Level Gauge', observedDepthCm: 72.0, modelPredCm: 70.8, deltaCm: -1.2, r2: 0.97, batteryPct: 98, status: 'CRITICAL_SURGE' },
  { id: 'SN-05', ward: 'H/East', location: 'BKC Culvert #4 (Kalanagar)', sensorType: 'Ultrasonic Pulse', observedDepthCm: 22.4, modelPredCm: 23.0, deltaCm: +0.6, r2: 0.98, batteryPct: 86, status: 'NOMINAL' },
  { id: 'SN-06', ward: 'K/East', location: 'Andheri Subway Underpass', sensorType: 'Radar + Optical Watermark', observedDepthCm: 84.5, modelPredCm: 82.0, deltaCm: -2.5, r2: 0.93, batteryPct: 95, status: 'CRITICAL_SURGE' }
];

export const DEMOGRAPHIC_WARD_EQUITY_DATA = [
  { ward: 'F/North (Dharavi / Sion)', vulnerabilityIndex: 'High (0.84)', informalSettlements: '64%', sensorDensity: '1.2 sensors/km²', modelCSI: '91.4%', mitigationBoost: '+14% Prioritization' },
  { ward: 'M/East (Govandi / Mankhurd)', vulnerabilityIndex: 'High (0.89)', informalSettlements: '78%', sensorDensity: '0.9 sensors/km²', modelCSI: '90.2%', mitigationBoost: '+18% Prioritization' },
  { ward: 'H/East (Kalanagar / Vakola)', vulnerabilityIndex: 'Moderate (0.61)', informalSettlements: '32%', sensorDensity: '2.1 sensors/km²', modelCSI: '94.8%', mitigationBoost: '+6% Prioritization' },
  { ward: 'A Ward (Colaba / Nariman Pt)', vulnerabilityIndex: 'Low (0.28)', informalSettlements: '6%', sensorDensity: '3.4 sensors/km²', modelCSI: '96.2%', mitigationBoost: 'Standard Baseline' },
  { ward: 'K/West (Andheri / Juhu)', vulnerabilityIndex: 'Moderate (0.58)', informalSettlements: '24%', sensorDensity: '2.6 sensors/km²', modelCSI: '94.1%', mitigationBoost: '+4% Prioritization' }
];

