// Domain constants & telemetry data for Mumbai Municipal Flood-Aware Mobility Command

export const MOBILITY_VEHICLES = [
  {
    id: 'ambulance',
    label: 'Ambulance (108 ALS)',
    category: 'Medical Critical',
    clearanceMm: 200,
    wadingMaxCm: 20,
    speedKmh: 48,
    priority: 'Level 1 Critical',
    intakeHeightCm: 45,
    curbWeightKg: 2850,
    icon: 'Ambulance',
    color: '#D94A4A',
    description: 'High-dependency patient transport. Zero tolerance for wading stall.',
  },
  {
    id: 'fire',
    label: 'Fire Rescue Tender',
    category: 'Heavy Rescue',
    clearanceMm: 500,
    wadingMaxCm: 50,
    speedKmh: 42,
    priority: 'Level 1 Rescue',
    intakeHeightCm: 110,
    curbWeightKg: 14500,
    icon: 'Flame',
    color: '#E06A26',
    description: 'High-ground clearance, snorkel-assisted air intake, high water torque.',
  },
  {
    id: 'police',
    label: 'Police 4x4 Quick Response',
    category: 'Law & Traffic',
    clearanceMm: 250,
    wadingMaxCm: 25,
    speedKmh: 55,
    priority: 'Level 2 Traffic',
    intakeHeightCm: 60,
    curbWeightKg: 2200,
    icon: 'Shield',
    color: '#2B6CB0',
    description: 'All-wheel drive patrol unit for corridor clearing and intersection hold.',
  },
  {
    id: 'transit',
    label: 'BEST Transit EV/CNG Bus',
    category: 'Public Commuter',
    clearanceMm: 350,
    wadingMaxCm: 35,
    speedKmh: 30,
    priority: 'Level 3 Commuter',
    intakeHeightCm: 75,
    curbWeightKg: 11200,
    icon: 'Bus',
    color: '#2F855A',
    description: 'Municipal bus evacuation carrier. High passenger payload.',
  },
  {
    id: 'heavy_crane',
    label: 'Heavy Recovery / Tow Crane',
    category: 'Clearance Equipment',
    clearanceMm: 750,
    wadingMaxCm: 75,
    speedKmh: 25,
    priority: 'Level 2 Equipment',
    intakeHeightCm: 140,
    curbWeightKg: 24000,
    icon: 'Wrench',
    color: '#805AD5',
    description: 'Heavy salvage unit to tow stalled civilian vehicles from flooded underpasses.',
  },
  {
    id: 'supply_truck',
    label: 'Emergency Relief Supply Truck',
    category: 'Logistics',
    clearanceMm: 400,
    wadingMaxCm: 40,
    speedKmh: 38,
    priority: 'Level 2 Logistics',
    intakeHeightCm: 90,
    curbWeightKg: 8500,
    icon: 'Truck',
    color: '#319795',
    description: 'Transport of dewatering pumps, sandbags, drinking water rations, and medical kits.',
  },
];

export const WAYPOINT_PRESETS = [
  {
    id: 'sion-hospital',
    name: 'Sion Municipal Trauma Hospital (LTMGH)',
    ward: 'Ward F/N',
    coordinates: [19.0384, 72.8612],
    type: 'Hospital / Critical Trauma',
    category: 'origin',
  },
  {
    id: 'andheri-relief',
    name: 'Andheri East Emergency Relief Camp (MIDC)',
    ward: 'Ward K/E',
    coordinates: [19.1136, 72.8697],
    type: 'Evacuation Shelter / Camp',
    category: 'destination',
  },
  {
    id: 'bkc-command',
    name: 'BKC MMRDA Disaster Control Cell',
    ward: 'Ward H/E',
    coordinates: [19.0664, 72.8677],
    type: 'Operational HQ',
    category: 'strategic',
  },
  {
    id: 'hindmata-junction',
    name: 'Hindmata Flyover Junction (Dadar)',
    ward: 'Ward F/S',
    coordinates: [19.0142, 72.8436],
    type: 'Lowland Choke Point',
    category: 'waypoint',
  },
  {
    id: 'milan-subway',
    name: 'Milan Subway West Ramp (Santacruz)',
    ward: 'Ward H/W',
    coordinates: [19.0883, 72.8427],
    type: 'Vulnerable Sump Underpass',
    category: 'hazard',
  },
  {
    id: 'kurla-station',
    name: 'Kurla West Railway Station / LBS Marg',
    ward: 'Ward L',
    coordinates: [19.0655, 72.8798],
    type: 'High Flood Risk Confluence',
    category: 'hazard',
  },
  {
    id: 'dadar-tt',
    name: 'Dadar TT Circle (Khodadad Circle)',
    ward: 'Ward F/N',
    coordinates: [19.0189, 72.8459],
    type: 'Key Central Intersection',
    category: 'transit',
  },
  {
    id: 'chembur-naka',
    name: 'Chembur Naka / Eastern Freeway Ramp',
    ward: 'Ward M/W',
    coordinates: [19.0592, 72.8985],
    type: 'Elevated Corridor Feeder',
    category: 'elevated',
  },
  {
    id: 'airport-cargo',
    name: 'Chhatrapati Shivaji Maharaj Cargo Terminal',
    ward: 'Ward K/E',
    coordinates: [19.0967, 72.8744],
    type: 'Logistics Air Hub',
    category: 'strategic',
  },
  {
    id: 'nair-hospital',
    name: 'Topiwala National Medical College / Nair Hospital',
    ward: 'Ward E',
    coordinates: [18.9715, 72.8222],
    type: 'South Trauma Center',
    category: 'hospital',
  },
];

export const ROUTE_PROFILES = [
  {
    id: 'standard',
    name: 'Standard Route (Direct via LBS Marg)',
    corridor: 'Sion &rarr; LBS Marg &rarr; Kurla &rarr; Sakinaka &rarr; Andheri East',
    distanceKm: 11.2,
    baseDurationMin: 23,
    flyoverPercentage: 15,
    maxFloodDepthCm: 34,
    hazardSegments: 3,
    status: 'IMPASSABLE FOR LIGHT FLEET',
    statusBadge: 'HIGH HAZARD',
    badgeColor: 'bg-status-alert text-white',
    description: 'Direct arterial route severely obstructed by 34cm standing water at Kurla West & Sakinaka drain backflows.',
    pathPoints: [
      [19.0384, 72.8612],
      [19.0520, 72.8710],
      [19.0655, 72.8798], // Kurla sump (34cm)
      [19.0830, 72.8830],
      [19.0980, 72.8780], // Sakinaka pooling (22cm)
      [19.1136, 72.8697],
    ],
    elevationProfile: [
      { km: 0.0, roadElevM: 6.2, waterDepthCm: 4, label: 'Sion Origin' },
      { km: 2.1, roadElevM: 5.4, waterDepthCm: 11, label: 'Kurla South' },
      { km: 4.3, roadElevM: 2.6, waterDepthCm: 34, label: 'Kurla LBS Sump (CRITICAL)' },
      { km: 6.8, roadElevM: 4.8, waterDepthCm: 18, label: 'Bail Bazar' },
      { km: 8.9, roadElevM: 3.5, waterDepthCm: 24, label: 'Sakinaka Junction' },
      { km: 11.2, roadElevM: 7.1, waterDepthCm: 0, label: 'Andheri East Camp' },
    ],
    chokePoints: [
      { name: 'Kurla LBS Railway Culvert', depthCm: 34, velocity: '0.85 m/s', risk: 'Severe Hydrolock Risk' },
      { name: 'Sakinaka Metro Pillar 42 Sump', depthCm: 24, velocity: '0.42 m/s', risk: 'Sediment Surcharge' },
    ],
  },
  {
    id: 'flood-aware',
    name: 'Recommended Flood-Aware Route (Elevated Flyovers)',
    corridor: 'Sion &rarr; Eastern Express Hwy &rarr; JVLR Flyover Corridor &rarr; Andheri East',
    distanceKm: 13.8,
    baseDurationMin: 28,
    flyoverPercentage: 82,
    maxFloodDepthCm: 0,
    hazardSegments: 0,
    status: '100% FLOOD-IMMUNE & CLEAR',
    statusBadge: 'RECOMMENDED',
    badgeColor: 'bg-purple text-white',
    description: 'Prioritizes elevated grade separators, Eastern Express Highway flyovers, and JVLR elevated spans. Zero road submergence.',
    pathPoints: [
      [19.0384, 72.8612],
      [19.0490, 72.8800],
      [19.0750, 72.9050], // Amar Mahal Flyover
      [19.1020, 72.9180], // EEH Ghatkopar Elevated
      [19.1250, 72.8950], // JVLR Elevated Flyover
      [19.1136, 72.8697],
    ],
    elevationProfile: [
      { km: 0.0, roadElevM: 6.2, waterDepthCm: 0, label: 'Sion Origin' },
      { km: 2.8, roadElevM: 14.5, waterDepthCm: 0, label: 'Amar Mahal Flyover' },
      { km: 5.9, roadElevM: 16.2, waterDepthCm: 0, label: 'EEH Elevated Span' },
      { km: 8.7, roadElevM: 18.0, waterDepthCm: 0, label: 'JVLR Powai Flyover' },
      { km: 11.4, roadElevM: 12.4, waterDepthCm: 0, label: 'SEEPZ Ramp' },
      { km: 13.8, roadElevM: 7.1, waterDepthCm: 0, label: 'Andheri East Camp' },
    ],
    chokePoints: [],
  },
  {
    id: 'emergency',
    name: 'Heavy Clearance Emergency Route (BKC - Milan Link)',
    corridor: 'Sion &rarr; BKC Connector &rarr; WEH &rarr; Milan Elevated &rarr; Andheri East',
    distanceKm: 12.6,
    baseDurationMin: 25,
    flyoverPercentage: 65,
    maxFloodDepthCm: 14,
    hazardSegments: 1,
    status: '4x4 / HIGH CLEARANCE ONLY',
    statusBadge: 'CONTROLLED ACCESS',
    badgeColor: 'bg-status-warning text-white',
    description: 'Utilizes BKC Elevated Connector with shallow 12-14cm sheet flow at Kalina university crossing. Passable for heavy tenders and 4x4.',
    pathPoints: [
      [19.0384, 72.8612],
      [19.0550, 72.8650],
      [19.0680, 72.8590], // BKC Elevated
      [19.0850, 72.8490], // Kalina sheet flow (14cm)
      [19.1000, 72.8550], // WEH Flyover
      [19.1136, 72.8697],
    ],
    elevationProfile: [
      { km: 0.0, roadElevM: 6.2, waterDepthCm: 2, label: 'Sion Origin' },
      { km: 2.4, roadElevM: 12.0, waterDepthCm: 0, label: 'BKC Connector Ramp' },
      { km: 5.1, roadElevM: 4.2, waterDepthCm: 14, label: 'Kalina Depot Dip' },
      { km: 7.8, roadElevM: 13.5, waterDepthCm: 0, label: 'WEH Santacruz Flyover' },
      { km: 10.2, roadElevM: 11.8, waterDepthCm: 0, label: 'Airport Approach' },
      { km: 12.6, roadElevM: 7.1, waterDepthCm: 0, label: 'Andheri East Camp' },
    ],
    chokePoints: [
      { name: 'Kalina Depot Surface Dip', depthCm: 14, velocity: '0.31 m/s', risk: 'Minor Traction Loss' },
    ],
  },
  {
    id: 'coastal-freeway',
    name: 'Eastern Freeway & Coastal Bypass Route',
    corridor: 'Sion &rarr; Chembur &rarr; Eastern Freeway &rarr; Ghatkopar Link &rarr; Andheri East',
    distanceKm: 15.4,
    baseDurationMin: 32,
    flyoverPercentage: 90,
    maxFloodDepthCm: 0,
    hazardSegments: 0,
    status: 'TIDAL LOCKOUT RESILIENT',
    statusBadge: 'ULTRA SAFE',
    badgeColor: 'bg-status-safe text-white',
    description: 'Fully grade-separated coastal highway bypass engineered above the 100-year extreme tide level (+7.5m MSL).',
    pathPoints: [
      [19.0384, 72.8612],
      [19.0510, 72.8890],
      [19.0620, 72.9150],
      [19.0950, 72.9280],
      [19.1210, 72.9050],
      [19.1136, 72.8697],
    ],
    elevationProfile: [
      { km: 0.0, roadElevM: 6.2, waterDepthCm: 0, label: 'Sion Origin' },
      { km: 3.5, roadElevM: 19.5, waterDepthCm: 0, label: 'Eastern Freeway Viaduct' },
      { km: 7.8, roadElevM: 22.0, waterDepthCm: 0, label: 'Anik Panjarpol Link' },
      { km: 11.2, roadElevM: 17.5, waterDepthCm: 0, label: 'Mankhurd Flyover' },
      { km: 15.4, roadElevM: 7.1, waterDepthCm: 0, label: 'Andheri East Camp' },
    ],
    chokePoints: [],
  },
];

// Vulnerable subways and sumps with live SCADA sensor readings
export const UNDERPASS_SUMPS = [
  {
    id: 'andheri-subway',
    name: 'Andheri Subway Underpass',
    ward: 'Ward K/E',
    waterDepthCm: 48,
    dangerThresholdCm: 25,
    pumpCapacityLps: 350,
    activePumps: 2,
    totalPumps: 3,
    gateStatus: 'CLOSED',
    flashingBeacon: 'RED BLINKING',
    trafficDivertedTo: 'Gokhale Bridge Flyover',
    lastUpdated: 'Just now',
    sensors: { ultrasonic: 48.2, hydroPressure: 47.9, siltLevelCm: 12 },
  },
  {
    id: 'milan-subway',
    name: 'Milan Subway (Santacruz)',
    ward: 'Ward H/W',
    waterDepthCm: 22,
    dangerThresholdCm: 20,
    pumpCapacityLps: 500,
    activePumps: 3,
    totalPumps: 4,
    gateStatus: 'RESTRICTED (4x4 Only)',
    flashingBeacon: 'AMBER WARNING',
    trafficDivertedTo: 'Milan Flyover Overpass',
    lastUpdated: '1 min ago',
    sensors: { ultrasonic: 22.1, hydroPressure: 21.8, siltLevelCm: 8 },
  },
  {
    id: 'khar-subway',
    name: 'Khar Subway Crossing',
    ward: 'Ward H/W',
    waterDepthCm: 36,
    dangerThresholdCm: 20,
    pumpCapacityLps: 200,
    activePumps: 1,
    totalPumps: 2,
    gateStatus: 'CLOSED',
    flashingBeacon: 'RED BLINKING',
    trafficDivertedTo: 'Bandra Reclamation Link',
    lastUpdated: '2 min ago',
    sensors: { ultrasonic: 36.4, hydroPressure: 35.9, siltLevelCm: 15 },
  },
  {
    id: 'hindmata-sump',
    name: 'Hindmata Flyover Underbelly Sump',
    ward: 'Ward F/S',
    waterDepthCm: 18,
    dangerThresholdCm: 15,
    pumpCapacityLps: 600,
    activePumps: 4,
    totalPumps: 4,
    gateStatus: 'DIVERTED TO UPPER FLYOVER',
    flashingBeacon: 'AMBER WARNING',
    trafficDivertedTo: 'Dadar TT Elevated Viaduct',
    lastUpdated: 'Just now',
    sensors: { ultrasonic: 18.2, hydroPressure: 17.9, siltLevelCm: 5 },
  },
  {
    id: 'kings-circle',
    name: 'King\'s Circle Railway Bridge Underpass',
    ward: 'Ward F/N',
    waterDepthCm: 29,
    dangerThresholdCm: 20,
    pumpCapacityLps: 450,
    activePumps: 2,
    totalPumps: 3,
    gateStatus: 'CLOSED TO BUSES/CARS',
    flashingBeacon: 'RED BLINKING',
    trafficDivertedTo: 'Dr. Ambedkar Road Elevated',
    lastUpdated: '3 min ago',
    sensors: { ultrasonic: 29.0, hydroPressure: 28.7, siltLevelCm: 10 },
  },
];

// Active Emergency CAD fleet
export const ACTIVE_MOBILITY_FLEET = [
  {
    id: 'AMB-108-01',
    callsign: 'Trauma Responder 01',
    vehicleType: 'ambulance',
    assignedRoute: 'flood-aware',
    driver: 'Paramedic S. Shinde',
    contact: '+91 98201 10801',
    currentLocation: 'Amar Mahal Flyover Northbound',
    speedKmh: 46,
    lat: 19.0750,
    lng: 72.9050,
    fuelBatteryPercent: 88,
    currentWaterDepthCm: 0,
    status: 'ACTIVE RUN',
    etaMin: 14,
    destination: 'Andheri East Camp',
  },
  {
    id: 'FIRE-RES-04',
    callsign: 'Hazmat Rescue Tender 04',
    vehicleType: 'fire',
    assignedRoute: 'emergency',
    driver: 'Capt. R. Pawar',
    contact: '+91 98201 10104',
    currentLocation: 'BKC Elevated Link Km 4.2',
    speedKmh: 38,
    lat: 19.0680,
    lng: 72.8590,
    fuelBatteryPercent: 92,
    currentWaterDepthCm: 11,
    status: 'TRANSITING WATER',
    etaMin: 18,
    destination: 'Kurla West Evacuation Point',
  },
  {
    id: 'POLICE-QRT-09',
    callsign: 'Traffic Interceptor 09',
    vehicleType: 'police',
    assignedRoute: 'standard',
    driver: 'Inspector A. Deshmukh',
    contact: '+91 98201 10009',
    currentLocation: 'Kurla LBS Marg Junction',
    speedKmh: 0,
    lat: 19.0655,
    lng: 72.8798,
    fuelBatteryPercent: 74,
    currentWaterDepthCm: 32,
    status: 'ENFORCING BARRICADE',
    etaMin: 0,
    destination: 'Barricade Post B-04',
  },
  {
    id: 'NDRF-BOAT-02',
    callsign: 'NDRF Amphibious Carrier 02',
    vehicleType: 'heavy_crane',
    assignedRoute: 'standard',
    driver: 'Sub-Inspector M. Verma',
    contact: '+91 98201 11202',
    currentLocation: 'Sakinaka Metro Crossing',
    speedKmh: 18,
    lat: 19.0980,
    lng: 72.8780,
    fuelBatteryPercent: 81,
    currentWaterDepthCm: 22,
    status: 'DEWATERING ESCORT',
    etaMin: 22,
    destination: 'Bail Bazar Flood Pocket',
  },
  {
    id: 'BEST-BUS-EVAC-12',
    callsign: 'Commuter Evac Liner 12',
    vehicleType: 'transit',
    assignedRoute: 'flood-aware',
    driver: 'Sr. Pilot G. Kadam',
    contact: '+91 98201 10412',
    currentLocation: 'JVLR Elevated Span Km 9.5',
    speedKmh: 34,
    lat: 19.1250,
    lng: 72.8950,
    fuelBatteryPercent: 65,
    currentWaterDepthCm: 0,
    status: 'TRANSPORTING 42 CIVILIANS',
    etaMin: 8,
    destination: 'Andheri East Camp',
  },
];

// Preemption Green Wave Intersections
export const GREEN_WAVE_CORRIDORS = [
  { id: 'GW-01', name: 'Sion Hospital Gate Outbound', cycleSec: 90, preemptionStatus: 'GREEN LOCKED', countdownSec: 42, cameraLive: true },
  { id: 'GW-02', name: 'Priyadarshini Circle EEH Ramp', cycleSec: 120, preemptionStatus: 'GREEN LOCKED', countdownSec: 38, cameraLive: true },
  { id: 'GW-03', name: 'Amar Mahal Flyover On-Ramp', cycleSec: 90, preemptionStatus: 'PREEMPTION READY', countdownSec: 15, cameraLive: true },
  { id: 'GW-04', name: 'Ghatkopar EEH Junction', cycleSec: 110, preemptionStatus: 'PREEMPTION READY', countdownSec: 25, cameraLive: false },
  { id: 'GW-05', name: 'Vikhroli Kannamwar Nagar Cross', cycleSec: 90, preemptionStatus: 'PREEMPTION READY', countdownSec: 60, cameraLive: true },
  { id: 'GW-06', name: 'JVLR Powai Lake Gateway', cycleSec: 100, preemptionStatus: 'GREEN HOLD ACTIVE', countdownSec: 54, cameraLive: true },
  { id: 'GW-07', name: 'SEEPZ Andheri East Ramp End', cycleSec: 90, preemptionStatus: 'GREEN LOCKED', countdownSec: 72, cameraLive: true },
];

// Multimodal transit statuses during active flooding
export const MULTIMODAL_TRANSIT_STATUS = [
  {
    mode: 'Western Railway',
    line: 'Churchgate &harr; Virar',
    status: 'RESTRICTED SPEEDS (25 km/h)',
    waterDepthTrackCm: 14,
    chokeLocation: 'Matunga & Bandra Tracks',
    headwayMin: 18,
    passengerImpact: '45% Delay',
    color: 'text-status-warning',
    statusBg: 'bg-status-warning-soft',
  },
  {
    mode: 'Central Railway (Main)',
    line: 'CSMT &harr; Kalyan',
    status: 'SUSPENDED BETWEEN SION & KURLA',
    waterDepthTrackCm: 28,
    chokeLocation: 'Sion & Kurla Sump Tracks',
    headwayMin: 0,
    passengerImpact: 'Total Halt (Buses deployed)',
    color: 'text-status-alert',
    statusBg: 'bg-status-alert-soft',
  },
  {
    mode: 'Central Railway (Harbour)',
    line: 'CSMT &harr; Panvel',
    status: 'WATERLOGGED AT CHUNABHATTI',
    waterDepthTrackCm: 22,
    chokeLocation: 'GTB Nagar & Chunabhatti',
    headwayMin: 35,
    passengerImpact: '60% Delays',
    color: 'text-status-alert',
    statusBg: 'bg-status-alert-soft',
  },
  {
    mode: 'Mumbai Metro Line 1',
    line: 'Versova &harr; Ghatkopar (Elevated)',
    status: '100% OPERATIONAL (Elevated Viaduct)',
    waterDepthTrackCm: 0,
    chokeLocation: 'Zero Flooding (Elevated)',
    headwayMin: 3.5,
    passengerImpact: 'Overcrowded (+140% Load)',
    color: 'text-status-safe',
    statusBg: 'bg-status-safe-soft',
  },
  {
    mode: 'BEST Emergency Fleet',
    line: 'Route 108 & 340 Feeder Diversions',
    status: 'DIVERTED TO EEH FLYOVERS',
    waterDepthTrackCm: 5,
    chokeLocation: 'LBS Marg Bypassed',
    headwayMin: 10,
    passengerImpact: '18 Extra Buses in Service',
    color: 'text-purple',
    statusBg: 'bg-purple-soft',
  },
];

// Turn-by-Turn Maneuvers for the Recommended Flood-Aware Route
export const TURN_BY_TURN_GUIDANCE = [
  {
    step: 1,
    action: 'Depart',
    instruction: 'Depart Sion Trauma Hospital northbound onto Sulochana Shetty Marg',
    distanceM: 350,
    durationSec: 45,
    roadType: 'At Grade (Elev. 6.2m MSL)',
    waterHazardCm: 0,
    warning: 'Clear. Avoid curbside gutter pooling.',
    speedLimitKmh: 40,
  },
  {
    step: 2,
    action: 'Turn Right',
    instruction: 'Turn right onto Dr. Babasaheb Ambedkar Road towards Priyadarshini Circle',
    distanceM: 850,
    durationSec: 90,
    roadType: 'At Grade (Elev. 5.8m MSL)',
    waterHazardCm: 2,
    warning: 'Minor surface sheeting (2cm). Maintain lane center.',
    speedLimitKmh: 50,
  },
  {
    step: 3,
    action: 'Take Ramp',
    instruction: 'Ascend Eastern Express Highway Elevated Flyover Ramp',
    distanceM: 450,
    durationSec: 40,
    roadType: 'Elevated Flyover Ramp (Elev. +14m MSL)',
    waterHazardCm: 0,
    warning: '100% dry grade separator. High priority emergency lane.',
    speedLimitKmh: 65,
  },
  {
    step: 4,
    action: 'Continue Straight',
    instruction: 'Proceed along Eastern Express Highway past Amar Mahal Viaduct',
    distanceM: 4200,
    durationSec: 240,
    roadType: 'Elevated Highway Corridor',
    waterHazardCm: 0,
    warning: 'High-speed green wave active. Signals pre-cleared.',
    speedLimitKmh: 70,
  },
  {
    step: 5,
    action: 'Exit Ramp',
    instruction: 'Take Exit 8 towards Jogeshwari-Vikhroli Link Road (JVLR) Westbound',
    distanceM: 650,
    durationSec: 60,
    roadType: 'Elevated Connector Span',
    waterHazardCm: 0,
    warning: 'Clear. Kurla lowlands bypassed entirely.',
    speedLimitKmh: 50,
  },
  {
    step: 6,
    action: 'Continue Straight',
    instruction: 'Cross Powai Lake Elevated Viaduct on JVLR',
    distanceM: 3800,
    durationSec: 220,
    roadType: 'Elevated Viaduct (Elev. +18m MSL)',
    waterHazardCm: 0,
    warning: 'High wind gusts (42 km/h). Safe traction.',
    speedLimitKmh: 60,
  },
  {
    step: 7,
    action: 'Turn Left',
    instruction: 'Descend SEEPZ flyover ramp onto Central Road / MIDC Andheri East',
    distanceM: 1200,
    durationSec: 110,
    roadType: 'At Grade High-Ridge (Elev. 7.1m MSL)',
    waterHazardCm: 0,
    warning: 'Clear drainage. Police marshal guiding convoy.',
    speedLimitKmh: 45,
  },
  {
    step: 8,
    action: 'Arrive',
    instruction: 'Arrive at Andheri East Emergency Relief Camp Gate 2',
    distanceM: 200,
    durationSec: 30,
    roadType: 'Camp Staging Ground',
    waterHazardCm: 0,
    warning: 'Destination reached safely with zero flood exposure.',
    speedLimitKmh: 20,
  },
];

// Historical flood benchmark events for route corridor
export const HISTORICAL_FLOOD_BENCHMARKS = [
  {
    year: '2005 (July 26)',
    rainfallMm24h: 944,
    kurlaLbsDepthCm: 180,
    milanSubwayDepthCm: 240,
    passability: 'TOTAL REGIONAL GRIDLOCK',
    strandedVehicles: 3400,
    lessons: 'Initiated construction of Milan Flyover and Mithi river desilting widening.',
  },
  {
    year: '2017 (August 29)',
    rainfallMm24h: 331,
    kurlaLbsDepthCm: 85,
    milanSubwayDepthCm: 110,
    passability: 'ALL AT-GRADE SUBWAYS SHUT',
    strandedVehicles: 720,
    lessons: 'Mandated automated flood barriers and radar-guided transit diversions.',
  },
  {
    year: '2021 (July 16)',
    rainfallMm24h: 235,
    kurlaLbsDepthCm: 52,
    milanSubwayDepthCm: 65,
    passability: 'DIVERTED TO EEH / WEH',
    strandedVehicles: 185,
    lessons: 'Proved elevated flyover routing cuts emergency response delay by 73%.',
  },
  {
    year: '2023 (July 22)',
    rainfallMm24h: 204,
    kurlaLbsDepthCm: 41,
    milanSubwayDepthCm: 50,
    passability: 'CONTROLLED RESTRICTED TRANSIT',
    strandedVehicles: 64,
    lessons: 'Pre-emptive barricading of Milan & Andheri Subways prevented all passenger entrapments.',
  },
];

// Barricades and closure management
export const INITIAL_BARRICADES = [
  {
    id: 'BAR-01',
    roadName: 'LBS Marg at Kurla West Depot Cut',
    ward: 'Ward L',
    type: 'Hard Concrete & Sandbag Barrier',
    status: 'ACTIVE BARRICADE',
    reason: 'Water depth 34cm exceeding civilian vehicle intake limit',
    authorizedBy: 'BMC Ward Officer & Traffic DCP',
    diversionRoute: 'Divert traffic eastwards towards EEH Amar Mahal',
    timestamp: '18:15 IST',
  },
  {
    id: 'BAR-02',
    roadName: 'Andheri Subway Both Ramps',
    ward: 'Ward K/E',
    type: 'Automated Hydraulic Barrier Arm (LOWERED)',
    status: 'HYDRAULIC LOCKED',
    reason: 'Water depth 48cm with active backflow',
    authorizedBy: 'Automated SCADA Water Depth Sensor Trigger',
    diversionRoute: 'Use Gokhale Bridge & Teli Gali Flyover',
    timestamp: '18:40 IST',
  },
  {
    id: 'BAR-03',
    roadName: 'Milan Subway West Ramp',
    ward: 'Ward H/W',
    type: 'Police Chevrons & Flare Barricade',
    status: '4x4 / EMERGENCY VEHICLES ONLY',
    reason: 'Water depth 22cm - restricted clearance threshold',
    authorizedBy: 'Santacruz Traffic Division',
    diversionRoute: 'Civilian cars diverted to Milan Flyover',
    timestamp: '18:50 IST',
  },
  {
    id: 'BAR-04',
    roadName: 'Sion East Circle Lowland Slip Road',
    ward: 'Ward F/N',
    type: 'Mobile Steel Chevrons',
    status: 'ACTIVE BARRICADE',
    reason: 'Tidal backflow puddling at Ambedkar Rd crossing',
    authorizedBy: 'Matunga Traffic Post',
    diversionRoute: 'Direct traffic up onto Sion Flyover viaduct',
    timestamp: '19:05 IST',
  },
];

// Staging Depots and elevated safe zones
export const ELEVATED_STAGING_DEPOTS = [
  {
    id: 'DEPOT-01',
    name: 'BKC MMRDA Ground Staging Hub',
    elevationM: 11.5,
    capacityVehicles: 120,
    availableTowingCranes: 4,
    dewateringPumpsReserve: 8,
    emergencyFuelLiters: 15000,
    chargingPortsEV: 12,
    crewBeds: 60,
    status: 'OPERATIONAL 24/7',
  },
  {
    id: 'DEPOT-02',
    name: 'Kurla Elevated Bus Yard (Level +2)',
    elevationM: 9.8,
    capacityVehicles: 85,
    availableTowingCranes: 2,
    dewateringPumpsReserve: 5,
    emergencyFuelLiters: 8000,
    chargingPortsEV: 6,
    crewBeds: 40,
    status: 'OPERATIONAL 24/7',
  },
  {
    id: 'DEPOT-03',
    name: 'Parel KEM Hospital Emergency Deck',
    elevationM: 14.0,
    capacityVehicles: 45,
    availableTowingCranes: 1,
    dewateringPumpsReserve: 3,
    emergencyFuelLiters: 5000,
    chargingPortsEV: 4,
    crewBeds: 30,
    status: 'STANDBY',
  },
  {
    id: 'DEPOT-04',
    name: 'Andheri MIDC Fire Brigade Compound',
    elevationM: 8.5,
    capacityVehicles: 70,
    availableTowingCranes: 3,
    dewateringPumpsReserve: 6,
    emergencyFuelLiters: 12000,
    chargingPortsEV: 8,
    crewBeds: 50,
    status: 'OPERATIONAL 24/7',
  },
];

// Drone Aerial Reconnaissance Feeds
export const DRONE_RECON_FEEDS = [
  {
    id: 'DRONE-01',
    name: 'Skylark Falcon 4 (Kurla LBS Corridor)',
    altitudeM: 85,
    batteryPercent: 78,
    aiDetections: [
      { type: 'Submerged Car', count: 3, conf: '94%' },
      { type: 'Stalled Auto-rickshaw', count: 5, conf: '91%' },
      { type: 'Stranded Pedestrian Cluster', count: 12, conf: '96%' },
    ],
    videoLatencyMs: 140,
    thermalThermalPeakC: 28.4,
    streamUrl: 'rtsp://drone-fleet.mcgm.gov.in/live/stream_01',
  },
  {
    id: 'DRONE-02',
    name: 'Hexacopter Sentinel 2 (Andheri Subway Ramp)',
    altitudeM: 60,
    batteryPercent: 64,
    aiDetections: [
      { type: 'Flooded Underpass Ingress', count: 1, conf: '99%' },
      { type: 'Floating Debris Clog', count: 2, conf: '88%' },
    ],
    videoLatencyMs: 165,
    thermalThermalPeakC: 26.2,
    streamUrl: 'rtsp://drone-fleet.mcgm.gov.in/live/stream_02',
  },
];

// Roadbed structural distress & pavement washout index
export const ROADBED_PAVEMENT_RISK = [
  {
    segment: 'LBS Marg (Kurla Junction to Sheetla Devi)',
    pavementType: 'Flexible Bituminous',
    structuralIndex: 38, // 0-100
    potholeWashoutRisk: 'CRITICAL',
    openManholeRisk: '2 Dislodged Manhole Lids Detected by Hydro Sensor',
    heavyAxleRestriction: 'Max 6 Tons',
    recommendedAction: 'Immediate lane closure & orange marker buoys placed',
  },
  {
    segment: 'Eastern Express Highway Flyover Deck',
    pavementType: 'Reinforced Concrete Post-Tensioned',
    structuralIndex: 94,
    potholeWashoutRisk: 'NEGLIGIBLE',
    openManholeRisk: 'None (Gated Deck Scuppers)',
    heavyAxleRestriction: 'Up to 40 Tons Safe',
    recommendedAction: 'Safe for all emergency convoy classes',
  },
  {
    segment: 'Kalina Military Camp Road',
    pavementType: 'Mastic Asphalt on WBM Base',
    structuralIndex: 58,
    potholeWashoutRisk: 'MODERATE',
    openManholeRisk: 'Chambers Intact',
    heavyAxleRestriction: 'Max 16 Tons',
    recommendedAction: 'Maintain center-lane driving at 25 km/h',
  },
  {
    segment: 'JVLR Elevated Powai Link',
    pavementType: 'Segmental Concrete Box Girder',
    structuralIndex: 96,
    potholeWashoutRisk: 'ZERO',
    openManholeRisk: 'None',
    heavyAxleRestriction: 'Up to 50 Tons Safe',
    recommendedAction: 'Unrestricted high-speed emergency corridor',
  },
];

