// Hydrodynamic datasets, corridor profiles, and telemetry for Module 16 Intervention Lab

export const EXTENDED_INTERVENTIONS = [
  {
    id: 'int-pump-01',
    name: 'Deploy High-Capacity Mobile Pump (500 HP)',
    targetLocation: 'Sion Circle Underpass (Ward F/N)',
    category: 'Active Dewatering',
    capacity: '1,800 m³/hr discharge',
    capacityNum: 1800,
    setupTimeMin: 15,
    status: 'AVAILABLE',
    costScore: 'Low',
    costLakhs: 1.8,
    deltaDepthReductionCm: 14.5,
    clearanceTimeSavedHours: 1.8,
    affectedRoadRelief: 'Sion Circle & Ambedkar Rd Ingress Restored',
    coordinates: [19.0392, 72.8619],
    powerType: 'Diesel (Euro-6 Cummins)',
    fuelLiters: 140,
    flowRateM3s: 0.50,
  },
  {
    id: 'int-sluice-02',
    name: 'Open Mahim Tidal Bypass Auxiliary Sluice',
    targetLocation: 'Mahim Creek Outfall Gate 4',
    category: 'Hydraulic Diversion',
    capacity: '12.0 m³/s gravity relief',
    capacityNum: 43200,
    setupTimeMin: 5,
    status: 'ACTIVE / MONITORED',
    costScore: 'Zero (Automated)',
    costLakhs: 0.2,
    deltaDepthReductionCm: 9.0,
    clearanceTimeSavedHours: 1.2,
    affectedRoadRelief: 'LBS Marg Backwater Pressure Reduced',
    coordinates: [19.0435, 72.8421],
    powerType: 'SCADA Electric Actuator',
    fuelLiters: 0,
    flowRateM3s: 12.0,
  },
  {
    id: 'int-barrier-03',
    name: 'Deploy Rapid-Inflate Flood Barriers (200m)',
    targetLocation: 'Andheri Subway Eastern Approach',
    category: 'Surface Water Deflection',
    capacity: 'Deflects 0.8 m³/s overland runoff',
    capacityNum: 2880,
    setupTimeMin: 20,
    status: 'DEPLOYED',
    costScore: 'Low',
    costLakhs: 2.5,
    deltaDepthReductionCm: 18.0,
    clearanceTimeSavedHours: 2.4,
    affectedRoadRelief: 'Prevents Complete Underpass Submergence',
    coordinates: [19.1197, 72.8468],
    powerType: 'Pneumatic Air Compressor (Honda GX)',
    fuelLiters: 45,
    flowRateM3s: 0.80,
  },
  {
    id: 'int-basin-04',
    name: 'Divert Trunk Runoff to Dadar Holding Pond',
    targetLocation: 'Pramod Mahajan Park Underground Sump',
    category: 'Retention Storage',
    capacity: '32,000 m³ retention buffer',
    capacityNum: 16000,
    setupTimeMin: 2,
    status: 'ACTIVE',
    costScore: 'Zero',
    costLakhs: 0.4,
    deltaDepthReductionCm: 11.2,
    clearanceTimeSavedHours: 1.5,
    affectedRoadRelief: 'Hindmata Dadar Flyover Underpass Clear',
    coordinates: [19.0178, 72.8428],
    powerType: 'Gravity Siphon + Submersible Return Pumps',
    fuelLiters: 0,
    flowRateM3s: 4.4,
  },
  {
    id: 'int-pump-05',
    name: 'Deploy Dual Submersible Axial Siphons (350 HP)',
    targetLocation: 'Milan Subway Western Portal (Ward H/W)',
    category: 'Active Dewatering',
    capacity: '2,400 m³/hr discharge',
    capacityNum: 2400,
    setupTimeMin: 18,
    status: 'STANDBY',
    costScore: 'Moderate',
    costLakhs: 2.2,
    deltaDepthReductionCm: 16.0,
    clearanceTimeSavedHours: 2.1,
    affectedRoadRelief: 'SV Road to Western Express link kept passable',
    coordinates: [19.0912, 72.8431],
    powerType: 'Diesel-Gen Silent Mobile',
    fuelLiters: 110,
    flowRateM3s: 0.67,
  },
  {
    id: 'int-vac-06',
    name: 'Super-Sucker High-Pressure Desilting Flusher',
    targetLocation: 'LBS Marg Kurla Junction Box Culvert',
    category: 'Active Dewatering',
    capacity: 'Clears 450 m³/hr sludge bottleneck',
    capacityNum: 1200,
    setupTimeMin: 10,
    status: 'STANDBY',
    costScore: 'Moderate',
    costLakhs: 1.5,
    deltaDepthReductionCm: 8.5,
    clearanceTimeSavedHours: 1.0,
    affectedRoadRelief: 'Eliminates Box-Drain D-204 Backwater Surge',
    coordinates: [19.0645, 72.8835],
    powerType: 'Heavy Commercial Rig (Tata Prima)',
    fuelLiters: 80,
    flowRateM3s: 0.33,
  },
  {
    id: 'int-sluice-07',
    name: 'Haji Ali Bay Coastal Tide Gate Throttle',
    targetLocation: 'Worli-Haji Ali Drainage Canal Outfall',
    category: 'Hydraulic Diversion',
    capacity: '18.5 m³/s gravitational surge control',
    capacityNum: 66600,
    setupTimeMin: 5,
    status: 'MONITORED',
    costScore: 'Zero (SCADA)',
    costLakhs: 0.1,
    deltaDepthReductionCm: 7.0,
    clearanceTimeSavedHours: 0.9,
    affectedRoadRelief: 'Prevents Pedder Rd / Mahalaxmi backflow',
    coordinates: [18.9782, 72.8124],
    powerType: 'Hydraulic Piston Dual Actuation',
    fuelLiters: 0,
    flowRateM3s: 18.5,
  },
  {
    id: 'int-barrier-08',
    name: 'Quick-Deploy Modular Cofferdam Berm (150m)',
    targetLocation: 'King’s Circle Gandhi Market Curb',
    category: 'Surface Water Deflection',
    capacity: 'Deflects 0.6 m³/s street sheet flow',
    capacityNum: 2160,
    setupTimeMin: 25,
    status: 'STANDBY',
    costScore: 'Low',
    costLakhs: 1.9,
    deltaDepthReductionCm: 10.5,
    clearanceTimeSavedHours: 1.3,
    affectedRoadRelief: 'Guards Railway Track Culvert from Ingress',
    coordinates: [19.0315, 72.8582],
    powerType: 'Mechanical Interlocking Polyurethane',
    fuelLiters: 0,
    flowRateM3s: 0.60,
  },
];

export const CORRIDOR_HYDRODYNAMICS = {
  'sion-circle': {
    id: 'sion-circle',
    name: 'Sion East Circle Junction (Ambedkar Rd Crossing)',
    ward: 'Ward F/N',
    elevation: 3.8,
    catchmentAreaHa: 142,
    manningsN: 0.022,
    curbHeightCm: 18,
    axleCriticalCm: 32,
    unmitigatedPeak: 43.0,
    peakTime: '19:35 IST',
    cause: 'Mithi River Tidal Lockout + Surcharged Box Drain',
    coordinates: [19.0392, 72.8619],
    timeSeries: [
      { time: '18:00', baseline: 6, rainfallMm: 42 },
      { time: '18:30', baseline: 14, rainfallMm: 68 },
      { time: '19:00', baseline: 27, rainfallMm: 95 },
      { time: '19:35', baseline: 43, rainfallMm: 85 },
      { time: '20:00', baseline: 38, rainfallMm: 50 },
      { time: '20:30', baseline: 29, rainfallMm: 28 },
      { time: '21:00', baseline: 19, rainfallMm: 12 },
      { time: '21:30', baseline: 11, rainfallMm: 5 },
      { time: '22:00', baseline: 5, rainfallMm: 0 },
    ],
  },
  'andheri-subway': {
    id: 'andheri-subway',
    name: 'Andheri Subway (Underpass Corridor)',
    ward: 'Ward K/E',
    elevation: 2.8,
    catchmentAreaHa: 98,
    manningsN: 0.026,
    curbHeightCm: 15,
    axleCriticalCm: 30,
    unmitigatedPeak: 52.0,
    peakTime: '19:25 IST',
    cause: 'Topographic Sump + Stormwater Pump Throttle',
    coordinates: [19.1197, 72.8468],
    timeSeries: [
      { time: '18:00', baseline: 12, rainfallMm: 45 },
      { time: '18:30', baseline: 28, rainfallMm: 72 },
      { time: '19:00', baseline: 47, rainfallMm: 102 },
      { time: '19:25', baseline: 52, rainfallMm: 90 },
      { time: '20:00', baseline: 42, rainfallMm: 45 },
      { time: '20:30', baseline: 31, rainfallMm: 20 },
      { time: '21:00', baseline: 18, rainfallMm: 8 },
      { time: '21:30', baseline: 9, rainfallMm: 2 },
      { time: '22:00', baseline: 3, rainfallMm: 0 },
    ],
  },
  'lbs-marg': {
    id: 'lbs-marg',
    name: 'LBS Marg (Kurla to Ghatkopar Corridor)',
    ward: 'Ward L',
    elevation: 6.2,
    catchmentAreaHa: 210,
    manningsN: 0.024,
    curbHeightCm: 16,
    axleCriticalCm: 35,
    unmitigatedPeak: 31.0,
    peakTime: '19:20 IST',
    cause: 'Drainage Surcharge (Node D-204 Backflow)',
    coordinates: [19.0645, 72.8835],
    timeSeries: [
      { time: '18:00', baseline: 4, rainfallMm: 35 },
      { time: '18:30', baseline: 12, rainfallMm: 60 },
      { time: '19:00', baseline: 25, rainfallMm: 84 },
      { time: '19:20', baseline: 31, rainfallMm: 76 },
      { time: '20:00', baseline: 24, rainfallMm: 38 },
      { time: '20:30', baseline: 16, rainfallMm: 15 },
      { time: '21:00', baseline: 9, rainfallMm: 5 },
      { time: '21:30', baseline: 4, rainfallMm: 0 },
      { time: '22:00', baseline: 1, rainfallMm: 0 },
    ],
  },
  'milan-subway': {
    id: 'milan-subway',
    name: 'Milan Subway Underpass (Santacruz-Vile Parle)',
    ward: 'Ward H/W',
    elevation: 3.1,
    catchmentAreaHa: 75,
    manningsN: 0.020,
    curbHeightCm: 15,
    axleCriticalCm: 28,
    unmitigatedPeak: 48.0,
    peakTime: '19:15 IST',
    cause: 'Low Railway Invert + Catch Basin Choking',
    coordinates: [19.0912, 72.8431],
    timeSeries: [
      { time: '18:00', baseline: 8, rainfallMm: 40 },
      { time: '18:30', baseline: 22, rainfallMm: 78 },
      { time: '19:00', baseline: 41, rainfallMm: 98 },
      { time: '19:15', baseline: 48, rainfallMm: 82 },
      { time: '20:00', baseline: 36, rainfallMm: 40 },
      { time: '20:30', baseline: 22, rainfallMm: 18 },
      { time: '21:00', baseline: 12, rainfallMm: 4 },
      { time: '21:30', baseline: 5, rainfallMm: 0 },
      { time: '22:00', baseline: 2, rainfallMm: 0 },
    ],
  },
  'hindmata-dadar': {
    id: 'hindmata-dadar',
    name: 'Hindmata Flyover Junction (Dadar East)',
    ward: 'Ward G/N',
    elevation: 4.1,
    catchmentAreaHa: 130,
    manningsN: 0.021,
    curbHeightCm: 20,
    axleCriticalCm: 32,
    unmitigatedPeak: 36.0,
    peakTime: '19:40 IST',
    cause: 'High Tide Lockout + Britannia Outfall Choke',
    coordinates: [19.0178, 72.8428],
    timeSeries: [
      { time: '18:00', baseline: 5, rainfallMm: 38 },
      { time: '18:30', baseline: 16, rainfallMm: 65 },
      { time: '19:00', baseline: 29, rainfallMm: 88 },
      { time: '19:40', baseline: 36, rainfallMm: 70 },
      { time: '20:00', baseline: 30, rainfallMm: 45 },
      { time: '20:30', baseline: 18, rainfallMm: 22 },
      { time: '21:00', baseline: 10, rainfallMm: 8 },
      { time: '21:30', baseline: 4, rainfallMm: 0 },
      { time: '22:00', baseline: 1, rainfallMm: 0 },
    ],
  },
  'kings-circle': {
    id: 'kings-circle',
    name: 'King’s Circle Gandhi Market (Maheshwari Udyan)',
    ward: 'Ward F/N',
    elevation: 3.4,
    catchmentAreaHa: 88,
    manningsN: 0.023,
    curbHeightCm: 18,
    axleCriticalCm: 30,
    unmitigatedPeak: 39.0,
    peakTime: '19:30 IST',
    cause: 'Railway Culvert Cul-de-sac backwater',
    coordinates: [19.0315, 72.8582],
    timeSeries: [
      { time: '18:00', baseline: 7, rainfallMm: 40 },
      { time: '18:30', baseline: 19, rainfallMm: 70 },
      { time: '19:00', baseline: 33, rainfallMm: 92 },
      { time: '19:30', baseline: 39, rainfallMm: 80 },
      { time: '20:00', baseline: 31, rainfallMm: 48 },
      { time: '20:30', baseline: 20, rainfallMm: 20 },
      { time: '21:00', baseline: 11, rainfallMm: 6 },
      { time: '21:30', baseline: 5, rainfallMm: 0 },
      { time: '22:00', baseline: 2, rainfallMm: 0 },
    ],
  },
};

export const MOBILE_PUMP_FLEET_DATA = [
  {
    id: 'mpump-01',
    name: 'MCGM Heavy Diesel 500-HP #1',
    model: 'Kirloskar KS-500 Axial',
    ward: 'Ward F/N',
    currentLocation: 'Sion Underpass East Sump',
    status: 'RUNNING (92% LOAD)',
    rpm: 1750,
    flowRateM3h: 1800,
    fuelPercent: 78,
    hoseLengthM: 120,
    suctionLiftM: 4.2,
    overdrive: false,
    dispatchedTo: 'Sion Circle',
  },
  {
    id: 'mpump-02',
    name: 'Tractor-Mounted Mobile Pump #4',
    model: 'John Deere 65HP High-Head',
    ward: 'Ward K/E',
    currentLocation: 'Andheri Subway Service Road',
    status: 'RUNNING (100% LOAD)',
    rpm: 2100,
    flowRateM3h: 1200,
    fuelPercent: 62,
    hoseLengthM: 80,
    suctionLiftM: 3.8,
    overdrive: false,
    dispatchedTo: 'Andheri Subway',
  },
  {
    id: 'mpump-03',
    name: 'Submersible Axial Siphon #2',
    model: 'Flygt N-Technology 3300',
    ward: 'Ward H/W',
    currentLocation: 'Milan Subway West Sump',
    status: 'STANDBY (READY)',
    rpm: 0,
    flowRateM3h: 0,
    fuelPercent: 95,
    hoseLengthM: 150,
    suctionLiftM: 2.5,
    overdrive: false,
    dispatchedTo: 'Milan Subway',
  },
  {
    id: 'mpump-04',
    name: 'MMRDA Mutual-Aid Trailer Pump #9',
    model: 'Godwin HL250M Dri-Prime',
    ward: 'Ward L',
    currentLocation: 'Kurla Depot Staging Yard',
    status: 'EN ROUTE (ETA 8 min)',
    rpm: 0,
    flowRateM3h: 0,
    fuelPercent: 88,
    hoseLengthM: 200,
    suctionLiftM: 5.0,
    overdrive: false,
    dispatchedTo: 'LBS Marg Kurla',
  },
];

export const TIDAL_SCHEDULE_DATA = [
  { time: '17:00', heightM: 3.20, state: 'Ebb Tide (Falling)', gateStatus: 'OPEN FOR DISCHARGE' },
  { time: '18:00', heightM: 3.75, state: 'Flood Tide (Rising)', gateStatus: 'THROTTLED 60%' },
  { time: '19:00', heightM: 4.40, state: 'High Water Ingress', gateStatus: 'PARTIAL CLOSURE' },
  { time: '19:42', heightM: 4.87, state: 'SPRING HIGH TIDE PEAK', gateStatus: 'TIDAL LOCKOUT (CLOSED)' },
  { time: '20:30', heightM: 4.30, state: 'Receding Flood Tide', gateStatus: 'MONITORING BACKPRESSURE' },
  { time: '21:30', heightM: 3.50, state: 'Ebb Gravity Flow Restored', gateStatus: 'EMERGENCY DISCHARGE OPEN' },
  { time: '22:30', heightM: 2.60, state: 'Low Water Approaching', gateStatus: '100% UNRESTRICTED' },
];

export const DETENTION_BASINS_DATA = [
  {
    id: 'basin-dadar',
    name: 'Pramod Mahajan Park Holding Basin',
    location: 'Dadar West / Hindmata Basin',
    maxCapacityM3: 32000,
    currentStoredM3: 19400,
    fillPercent: 60.6,
    inflowM3s: 3.8,
    outflowPumpM3s: 1.2,
    headRoomMin: 55,
    status: 'ACTIVE BUFFERING',
  },
  {
    id: 'basin-milan',
    name: 'Milan Subway Underground Retention Tank',
    location: 'Milan Subway Junction',
    maxCapacityM3: 18000,
    currentStoredM3: 13500,
    fillPercent: 75.0,
    inflowM3s: 2.1,
    outflowPumpM3s: 0.9,
    headRoomMin: 35,
    status: 'NEAR CAPACITY (ALERT)',
  },
  {
    id: 'basin-gandhi',
    name: 'Gandhi Market Storm Sump Resevoir',
    location: 'King’s Circle / Matunga East',
    maxCapacityM3: 24000,
    currentStoredM3: 9800,
    fillPercent: 40.8,
    inflowM3s: 1.8,
    outflowPumpM3s: 1.5,
    headRoomMin: 120,
    status: 'OPTIMAL CLEARANCE',
  },
];

